import CollisionIdeals.Planar.ExplicitSecant
import CollisionIdeals.Planar.KellerFrame
import CollisionIdeals.Planar.Research.PrincipalPartsStrategy
import Mathlib.RingTheory.Localization.FractionRing
import Mathlib.RingTheory.Localization.Integer

/-!
# Finite coefficient and operator denominator ideals

This file formalizes two finite-denominator lemmas.  The finite-family result
matches the archived boundary manuscript's evaluated secant--frame coefficient lattice.  The
operator result applies to a `B`-linear map on a finite `B`-order; the Keller
frame is not `B`-linear for `B = ℂ[P,Q]`, so that theorem is auxiliary and
is not its specialization.

The theorem does **not** say that such a denominator carries the whole
fixed--moving principal-parts module into the trace-dual bounded stage.  That
uniform landing assertion is the remaining Keller-specific theorem.
-/

set_option autoImplicit false

namespace CollisionIdeals.Planar

noncomputable section

universe u v w

variable (B : Type u) [CommRing B]
variable (T : Type v) [CommRing T] [IsDomain T] [Algebra B T]
variable (N : Type w) [Field N] [Algebra T N] [Algebra B N]
variable [IsScalarTower B T N]

section FiniteCoefficients

/-- The `T`-submodule generated by a finite family of rational coefficients. -/
def finiteCoefficientSubmodule
    {n : ℕ} (coefficients : Fin n → N) : Submodule T N :=
  Submodule.span T (Set.range coefficients)

/-- The canonical ideal clearing a finite family of rational coefficients. -/
def finiteCoefficientDenominatorIdeal
    {n : ℕ} (coefficients : Fin n → N) : Ideal T :=
  (1 : Submodule T N).colon
    (finiteCoefficientSubmodule T N coefficients)

omit [IsDomain T] in
theorem mem_finiteCoefficientDenominatorIdeal_iff
    {n : ℕ} (coefficients : Fin n → N) (s : T) :
    s ∈ finiteCoefficientDenominatorIdeal T N coefficients ↔
      ∀ i, s • coefficients i ∈ (1 : Submodule T N) := by
  rw [finiteCoefficientDenominatorIdeal, Submodule.mem_colon]
  constructor
  · intro h i
    exact h _ (Submodule.subset_span (Set.mem_range_self i))
  · intro h x hx
    refine Submodule.span_induction
      (p := fun x _ => s • x ∈ (1 : Submodule T N)) ?_ ?_ ?_ ?_ hx
    · intro x hx
      obtain ⟨i, rfl⟩ := hx
      exact h i
    · simp
    · intro x y hx hy ihx ihy
      simpa [smul_add] using (1 : Submodule T N).add_mem ihx ihy
    · intro a x hx ih
      rw [smul_smul, mul_comm, ← smul_smul]
      exact (1 : Submodule T N).smul_mem a ih

omit [IsDomain T] in
private theorem mem_one_submodule_iff' (x : N) :
    x ∈ (1 : Submodule T N) ↔ ∃ t : T, algebraMap T N t = x := by
  rw [Submodule.one_eq_span]
  change x ∈ Submodule.span T {1} ↔ _
  rw [Submodule.mem_span_singleton]
  constructor
  · rintro ⟨t, rfl⟩
    exact ⟨t, by simp [Algebra.smul_def]⟩
  · rintro ⟨t, rfl⟩
    exact ⟨t, by simp [Algebra.smul_def]⟩

/-- A finite family in `Frac(T)` has a nonzero common denominator.  This is
the formal core of the archived boundary manuscript's nonzero secant--frame denominator
proposition. -/
theorem finiteCoefficientDenominatorIdeal_ne_bot
    [IsFractionRing T N]
    {n : ℕ} (coefficients : Fin n → N) :
    finiteCoefficientDenominatorIdeal T N coefficients ≠ ⊥ := by
  obtain ⟨denom, hdenom⟩ :=
    IsLocalization.exist_integer_multiples_of_finite
      (nonZeroDivisors T) coefficients
  have hmem :
      (denom : T) ∈ finiteCoefficientDenominatorIdeal T N coefficients := by
    rw [mem_finiteCoefficientDenominatorIdeal_iff]
    intro i
    apply (mem_one_submodule_iff' T N _).mpr
    exact hdenom i
  intro hbot
  rw [hbot] at hmem
  have hz : (denom : T) = 0 := hmem
  exact (mem_nonZeroDivisors_iff_ne_zero.mp denom.property) hz

end FiniteCoefficients

section LinearOperator

/-- Values of a `B`-linear operator on a finite `B`-order, spanned over `T`.
This is not directly applicable to the inverse-Jacobian Keller frame. -/
def linearOperatorImageSubmodule (D : T →ₗ[B] N) : Submodule T N :=
  Submodule.span T (Set.range D)

/-- The canonical ideal clearing every value of a linear operator back to `T`. -/
def linearOperatorDenominatorIdeal (D : T →ₗ[B] N) : Ideal T :=
  (1 : Submodule T N).colon (linearOperatorImageSubmodule B T N D)

omit [IsDomain T] [IsScalarTower B T N] in
theorem mem_linearOperatorDenominatorIdeal_iff
    (D : T →ₗ[B] N) (s : T) :
    s ∈ linearOperatorDenominatorIdeal B T N D ↔
      ∀ t : T, s • D t ∈ (1 : Submodule T N) := by
  rw [linearOperatorDenominatorIdeal, Submodule.mem_colon]
  constructor
  · intro h t
    exact h _ (Submodule.subset_span (Set.mem_range_self t))
  · intro h x hx
    refine Submodule.span_induction
      (p := fun x _ => s • x ∈ (1 : Submodule T N)) ?_ ?_ ?_ ?_ hx
    · intro x hx
      obtain ⟨t, rfl⟩ := hx
      exact h t
    · simp
    · intro x y hx hy ihx ihy
      simpa [smul_add] using (1 : Submodule T N).add_mem ihx ihy
    · intro a x hx ih
      rw [smul_smul, mul_comm, ← smul_smul]
      exact (1 : Submodule T N).smul_mem a ih

omit [IsDomain T] in
private theorem mem_one_submodule_iff (x : N) :
    x ∈ (1 : Submodule T N) ↔ ∃ t : T, algebraMap T N t = x := by
  rw [Submodule.one_eq_span]
  change x ∈ Submodule.span T {1} ↔ _
  rw [Submodule.mem_span_singleton]
  constructor
  · rintro ⟨t, rfl⟩
    exact ⟨t, by simp [Algebra.smul_def]⟩
  · rintro ⟨t, rfl⟩
    exact ⟨t, by simp [Algebra.smul_def]⟩

/-- Finite generation gives a nonzero common denominator for an operator on
a finite order inside its fraction field. -/
theorem linearOperatorDenominatorIdeal_ne_bot
    [Module.Finite B T] [IsFractionRing T N]
    (D : T →ₗ[B] N) :
    linearOperatorDenominatorIdeal B T N D ≠ ⊥ := by
  obtain ⟨n, generators, hgen⟩ := Module.Finite.exists_fin (R := B) (M := T)
  obtain ⟨denom, hdenom⟩ :=
    IsLocalization.exist_integer_multiples_of_finite
      (nonZeroDivisors T) (fun i : Fin n => D (generators i))
  have hmem :
      (denom : T) ∈ linearOperatorDenominatorIdeal B T N D := by
    rw [mem_linearOperatorDenominatorIdeal_iff]
    intro t
    have ht : t ∈ Submodule.span B (Set.range generators) := by
      rw [hgen]
      trivial
    refine Submodule.span_induction (p := fun t _ =>
      (denom : T) • D t ∈ (1 : Submodule T N)) ?_ ?_ ?_ ?_ ht
    · intro x hx
      obtain ⟨i, rfl⟩ := hx
      apply (mem_one_submodule_iff T N _).mpr
      exact hdenom i
    · simp
    · intro x y hx hy ihx ihy
      rw [map_add, smul_add]
      exact (1 : Submodule T N).add_mem ihx ihy
    · intro b x hx ih
      rw [LinearMap.map_smul, smul_comm]
      have hb := (1 : Submodule T N).smul_mem (algebraMap B T b) ih
      rwa [IsScalarTower.algebraMap_smul T b] at hb
  intro hbot
  rw [hbot] at hmem
  have hz : (denom : T) = 0 := hmem
  exact (mem_nonZeroDivisors_iff_ne_zero.mp denom.property) hz

/-- Two `B`-linear operators admit one simultaneous nonzero denominator. -/
theorem exists_nonzero_mem_both_linearOperatorDenominatorIdeals
    [Module.Finite B T] [IsFractionRing T N]
    (D₀ D₁ : T →ₗ[B] N) :
    ∃ s : T, s ≠ 0 ∧
      s ∈ linearOperatorDenominatorIdeal B T N D₀ ∧
      s ∈ linearOperatorDenominatorIdeal B T N D₁ := by
  have h₀ := linearOperatorDenominatorIdeal_ne_bot B T N D₀
  have h₁ := linearOperatorDenominatorIdeal_ne_bot B T N D₁
  obtain ⟨s₀, hs₀mem, hs₀⟩ :
      ∃ s₀ : T, s₀ ∈ linearOperatorDenominatorIdeal B T N D₀ ∧ s₀ ≠ 0 := by
    by_contra h
    push_neg at h
    apply h₀
    ext x
    constructor
    · intro hx
      exact h x hx
    · intro hx
      have hx0 : x = 0 := hx
      simp [hx0]
  obtain ⟨s₁, hs₁mem, hs₁⟩ :
      ∃ s₁ : T, s₁ ∈ linearOperatorDenominatorIdeal B T N D₁ ∧ s₁ ≠ 0 := by
    by_contra h
    push_neg at h
    apply h₁
    ext x
    constructor
    · intro hx
      exact h x hx
    · intro hx
      have hx0 : x = 0 := hx
      simp [hx0]
  refine ⟨s₀ * s₁, mul_ne_zero hs₀ hs₁, ?_, ?_⟩
  · exact
      (linearOperatorDenominatorIdeal B T N D₀).mul_mem_right s₁ hs₀mem
  · exact
      (linearOperatorDenominatorIdeal B T N D₁).mul_mem_left s₀ hs₁mem

end LinearOperator

end

end CollisionIdeals.Planar
