import CollisionIdeals.General.Normalization.BaseTransversality
import CollisionIdeals.General.Normalization.SimplePole
import CollisionIdeals.General.Normalization.ConormalDerivation
import CollisionIdeals.General.Galois.ConjugateAlgebra
import CollisionIdeals.General.Normalization.DerivationCriterion
import CollisionIdeals.General.Keller.DivisorVisibility
import CollisionIdeals.General.Keller.MonomialWeights
import CollisionIdeals.General.Normalization.VisibleConjugateCenter
import CollisionIdeals.Planar.Research.Vanishing.BaseFrame
import CollisionIdeals.Planar.Research.Vanishing.FrameDenominator
import CollisionIdeals.Planar.Research.Vanishing.SecantReduction
import CollisionIdeals.Planar.Research.Vanishing.ConductorComparison
import CollisionIdeals.Planar.Research.Vanishing.ConductorLocalization
import CollisionIdeals.Planar.Research.Vanishing.GeneratorDerivative
import CollisionIdeals.Planar.Research.Vanishing.LocalizedJacobianDiagnostic
import CollisionIdeals.Planar.Research.Vanishing.LocalCollision
import CollisionIdeals.Planar.Research.Vanishing.InertiaCoordinates
import CollisionIdeals.Planar.Research.Vanishing.GaloisDescent
import CollisionIdeals.Planar.Research.Vanishing.Ramification
import CollisionIdeals.Planar.Research.PrincipalPartsStrategy
import CollisionIdeals.Planar.Research.FixedMovingBoundaryPrincipalParts
import CollisionIdeals.Planar.Research.FinitePrincipalPartsControl
import CollisionIdeals.Planar.ConjugateSecantEvaluation
import CollisionIdeals.Planar.ExplicitSecant
import CollisionIdeals.Planar.KellerFrame
import CollisionIdeals.Planar.Research.SecantFrameDenominator
import CollisionIdeals.Planar.Research.FiniteDenominatorCounterexample
import CollisionIdeals.Planar.Research.KellerFrameExtension
import CollisionIdeals.Planar.Research.BoundarySections
import CollisionIdeals.Planar.Research.BoundarySectionLocalization
import CollisionIdeals.Planar.Research.LocalizationDenominator
import CollisionIdeals.Planar.Research.HeightOneBoundaryPole
import CollisionIdeals.Planar.Research.NormalizationTraceBound
import CollisionIdeals.Planar.Research.BoundaryPoleWitness
import CollisionIdeals.Planar.Research.SecantFrameCandidate
import CollisionIdeals.Planar.Research.MonogenicOrder
import CollisionIdeals.Planar.Research.MonogenicTraceDual
import CollisionIdeals.Planar.Research.TateReconstruction
import CollisionIdeals.Planar.Research.MonogenicLanding
import CollisionIdeals.Planar.Research.TraceLanding
import CollisionIdeals.Planar.Research.SecantFrameTraceLanding
import CollisionIdeals.Planar.Research.CompletedTameRamification

/-!
# Planar vanishing research

The central theorem target is the existing `CollisionIdeals.PlanarVanishing`:
the collision obstruction vanishes for every planar Keller map. Divisorial
unramifiedness and boundary/trace landing are possible routes to that goal,
not replacements for it. The full target has no generic-degree restriction.

`Planar/Research/Vanishing/README.md` indexes the primary proof spine and the
object bench. The spine records the missing planar implication and the
conditional endgame; the bench records what each construction contributes,
alternative routes, and negative controls. Existing definitions and import
paths are retained rather than duplicated for the research organization.

This umbrella keeps the experimental modules separate from the public
`CollisionIdeals.Planar` import spine. The available work includes:

* the actual algebra generated by all conjugate source coordinates is
  constructed over the coordinate-image base; it contains every conjugate
  polynomial sheet, is Galois-stable, and has finite type. Module-finiteness,
  the invariant-open identification, and its boundary are not inferred;
* the active finite boundary test uses two components of Mathlib's existing
  conormal module. Their vanishing is equivalent to ideal preservation,
  hence to the unit ideal over a characteristic-zero polynomial base. The
  actual Keller-specific conormal vanishing remains open;
* a derivation regular in the actual prime localization and transverse to
  a base element forces local index one, hence unramifiedness at a DVR prime
  with separable residue extension;
* every nonzero proper polynomial ideal in characteristic zero has a
  transverse coordinate partial; the actual Keller frames recover target
  partial derivatives on arbitrary target polynomials, also after extension
  to the normal closure. Regularity at a boundary prime is not supplied;
* preserving the cyclic simple-pole module with denominator `s` is
  equivalent to preserving the principal ideal `(s)`. This tests a proposed
  boundary invariant; finite clearing of secant first jets does not prove
  its preservation or identify their denominator with the reduced boundary;
* clearing a derivation on finite module generators clears the whole order
  by Leibniz, without incorrectly treating the frame as base-linear;
* in dimension two the adjugate and its first jets add no generators to the
  evaluated secant lattice and do not change its denominator ideal;
* control of a monogenic generator gives a conductor-multiplied comparison
  for all normalization derivatives. Once a conductor element is inverted,
  generator control is equivalent to control of all derivatives;
* differentiating the generator's minimal polynomial retains the varying
  base coefficients and identifies the exact missing divisibility by the
  monogenic Jacobian. Separability gives nonzero Jacobian, not local
  invertibility or the required divisibility;
* the actual polynomial source reflects units from its coordinate-image
  base. Keller flatness and factorization produce a visible unramified
  source divisor over every height-one base prime; this is existence of one
  sheet, not unramifiedness of every normal-closure sheet;
* lying-over and Galois transitivity realize that source divisor as an
  actual conjugate center. With the supplied local-index realization, its
  sheet is fixed by inertia; this does not make inertia trivial;
* two local Keller collision maps with equal coordinate residues coincide.
  Applied directly to valuation inertia, this forces a nonregular source
  coordinate on every inertia-moved sheet, without an index realization.
  Closure does not supply the missing source-coordinate regularity;
* in every dimension, each source variable occurs as a nonzero linear
  coefficient of some Keller component. Nonnegative integer weights on
  all component supports therefore force nonnegative coordinate weights.
  Regularity for an arbitrary valuation does not supply the support premise;
* descent of all conjugate source coordinates to the marked original field
  is equivalent to normality of that original extension. The planar target
  is stated explicitly and implies obstruction vanishing with the accepted
  Keller--Galois rigidity input; descent itself remains unproved. Its failure
  supplies a conjugate coordinate moved by an element fixing the original
  field, not an inertia or residue-agreement witness;
* an explicit rational-plane diagnostic has determinant one in coordinates
  on a proper open source, while its target-dual derivative is not in the
  polynomial normalization ring. It is not a polynomial Keller map on the
  whole affine plane. Its cubic variant even reaches every complex target
  point, so existence of a visible sheet alone does not repair the gap;
* the direct no-ramification endgame uses the canonical finite normalized
  cover constructed from the Keller condition, without requiring the larger
  collision model's conjugate-center and inertia-index realization;
* a removed height-one fixed--moving prime produces an actual section
  outside the normalization ring, by localized ideal-power containment and
  finite denominator clearing;
* the generic trace-integral carrier is Mathlib's trace dual, and an integral
  generic basis supplies a nonzero denominator for its full normalization
  specialization;
* the polynomial Keller frame extends to the source fraction field and
  marked normal closure, preserves each conjugate polynomial sheet, and
  supplies the actual secant/adjugate first jets with a nonzero denominator;
* the genuine section ring of the fixed--moving open complement embeds in
  the normal-closure field, defining the boundary-section subalgebra;
* bounded-overring rigidity proves the global section pole witness: at a
  height-one fixed--moving prime, every nonzero multiplier fails the trace
  test on some actual section; no local-cohomology comparison is needed;
* a chosen integral primitive generator for the secant--trace comparison uses
  Mathlib's monogenic order, power basis, hypersurface presentation, Jacobian
  element, and conductor directly;
* finite Tate reconstruction and the generic monogenic/overorder
  trace-dual--conductor identities are proved;
* the monogenic conductor stage and its actual transporter ideal are defined,
  a generic normal-Noetherian finite-overring collapse is proved, and an
  explicit pointwise pole witness plus a nonzero landing candidate is proved
  to imply boundary separation and the existing planar endgame;
* independently of the monogenic comparison, the trace-integral dual and its
  transporter are specialized to the normalization diagram; the concrete
  section ring and secant--frame ideal are wired to boundary separation and
  collision vanishing for a supplied model and the stated literature inputs,
  conditional on landing for prime-order subgroups (sufficient by the proved
  Cauchy reduction), with the pole witness derived;
* the missing Keller-specific theorem says that this prescribed ideal is
  contained in the trace transporter for the whole pole tower;
* the landing audit separates finite coefficient clearing from uniform
  control: an explicit polynomial negative control has a nonzero finite
  denominator but zero overring transporter, and the actual secant--frame
  containment is proved to force `R_C = T`;
* the tame local calculation leaves inertia-invariant poles at all
  multiples of the ramification index. A logarithmic eigenvalue identity
  does not remove these poles or give the missing uniform bound.

On the alternative trace route, the missing containment is not packaged as
another abstract bridge here. Proving it requires a Keller-specific argument
controlling all sections, not just a nonzero finite denominator. On the active
finite route, the missing comparison concerns the two actual boundary
conormal classes; it is not a whole-pole-tower bound. Neither route's
conditional endgame nor the model construction proves planar vanishing.
-/
