import CollisionIdeals.General.ResidualCollision.Algebra
import CollisionIdeals.Planar.Basic
import CollisionIdeals.Planar.Secant.Algebra
import CollisionIdeals.Planar.Secant.Ideal

set_option autoImplicit false
set_option maxHeartbeats 800000

namespace CollisionIdeals

open MvPolynomial

noncomputable section

universe u

variable {R : Type u} [CommRing R]

/-- In two variables, the diagonal ideal is generated by the two coordinate differences. -/
theorem diagonalIdeal_fin_two_eq_span_pair :
    diagonalIdeal (R := R) (ι := Fin 2) =
      Ideal.span
        ({diagonalGenerator (R := R) 0,
          diagonalGenerator (R := R) 1} :
          Set (PairRing R (Fin 2))) := by
  rw [diagonalIdeal]
  congr 1
  ext z
  constructor
  · rintro ⟨i, rfl⟩
    fin_cases i <;> simp
  · intro hz
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hz
    rcases hz with rfl | rfl
    · exact Set.mem_range_self 0
    · exact Set.mem_range_self 1

/--
Every planar polynomial has a two-coordinate secant decomposition whose
coefficients restrict on the diagonal to the two formal partial derivatives.
-/
theorem exists_planarSecantCoefficients
    (p : SourceRing R (Fin 2)) :
    ∃ a b : PairRing R (Fin 2),
      leftRename p - rightRename p =
          a * diagonalGenerator (R := R) 0 +
            b * diagonalGenerator (R := R) 1 ∧
      diagonalEval a = pderiv 0 p ∧
      diagonalEval b = pderiv 1 p := by
  induction p using MvPolynomial.induction_on with
  | C r =>
      exact ⟨0, 0, by simp, by simp, by simp⟩
  | add p q hp hq =>
      obtain ⟨ap, bp, hpEq, hpa, hpb⟩ := hp
      obtain ⟨aq, bq, hqEq, hqa, hqb⟩ := hq
      refine ⟨ap + aq, bp + bq, ?_, ?_, ?_⟩
      · rw [map_add, map_add]
        calc
          leftRename p + leftRename q -
              (rightRename p + rightRename q) =
            (leftRename p - rightRename p) +
              (leftRename q - rightRename q) := by ring
          _ = _ := by rw [hpEq, hqEq]; ring
      · simp [hpa, hqa]
      · simp [hpb, hqb]
  | mul_X p i hp =>
      obtain ⟨a, b, hpEq, ha, hb⟩ := hp
      fin_cases i
      · let xr : PairRing R (Fin 2) := X (Sum.inr 0)
        refine ⟨leftRename p + a * xr, b * xr, ?_, ?_, ?_⟩
        · rw [map_mul, map_mul, leftRename_X, rightRename_X]
          change
            leftRename p * X (Sum.inl 0) -
                rightRename p * X (Sum.inr 0) =
              (leftRename p + a * xr) *
                  diagonalGenerator (R := R) 0 +
                (b * xr) * diagonalGenerator (R := R) 1
          rw [show
            leftRename p * X (Sum.inl 0) -
                rightRename p * X (Sum.inr 0) =
              leftRename p * diagonalGenerator (R := R) 0 +
                (leftRename p - rightRename p) * xr by
                  simp [diagonalGenerator, xr]
                  ring,
            hpEq]
          ring
        · rw [map_add, map_mul, diagonalEval_leftRename, ha]
          simp [xr, diagonalEval]
          ring
        · rw [map_mul, hb]
          simp [xr, diagonalEval]
          ring
      · let yr : PairRing R (Fin 2) := X (Sum.inr 1)
        refine ⟨a * yr, leftRename p + b * yr, ?_, ?_, ?_⟩
        · rw [map_mul, map_mul, leftRename_X, rightRename_X]
          change
            leftRename p * X (Sum.inl 1) -
                rightRename p * X (Sum.inr 1) =
              (a * yr) * diagonalGenerator (R := R) 0 +
                (leftRename p + b * yr) *
                  diagonalGenerator (R := R) 1
          rw [show
            leftRename p * X (Sum.inl 1) -
                rightRename p * X (Sum.inr 1) =
              leftRename p * diagonalGenerator (R := R) 1 +
                (leftRename p - rightRename p) * yr by
                  simp [diagonalGenerator, yr]
                  ring,
            hpEq]
          ring
        · rw [map_mul, ha]
          simp [yr, diagonalEval]
          ring
        · rw [map_add, map_mul, diagonalEval_leftRename, hb]
          simp [yr, diagonalEval]
          ring

/-- A secant decomposition of one planar polynomial with its diagonal values. -/
structure PlanarSecantData
    (p : SourceRing R (Fin 2)) where
  first : PairRing R (Fin 2)
  second : PairRing R (Fin 2)
  equation :
    leftRename p - rightRename p =
      first * diagonalGenerator (R := R) 0 +
        second * diagonalGenerator (R := R) 1
  diagonal_first :
    diagonalEval first = pderiv 0 p
  diagonal_second :
    diagonalEval second = pderiv 1 p

/-- Every planar polynomial admits secant data. -/
theorem nonempty_planarSecantData
    (p : SourceRing R (Fin 2)) :
    Nonempty (PlanarSecantData p) := by
  obtain ⟨a, b, hab, ha, hb⟩ :=
    exists_planarSecantCoefficients p
  exact ⟨⟨a, b, hab, ha, hb⟩⟩

/-- The determinant attached to any two choices of planar secant data
annihilates the diagonal ideal modulo the corresponding collision ideal. -/
theorem secantDataDet_mul_diagonalIdeal_mem_collisionIdeal
    (F : Fin 2 → SourceRing R (Fin 2))
    (d₀ : PlanarSecantData (F 0))
    (d₁ : PlanarSecantData (F 1))
    (z : PairRing R (Fin 2))
    (hz : z ∈ diagonalIdeal (R := R) (ι := Fin 2)) :
    secantDet d₀.first d₀.second d₁.first d₁.second * z ∈
      collisionIdeal F := by
  have hz' :
      z ∈ Ideal.span
        ({diagonalGenerator (R := R) 0,
          diagonalGenerator (R := R) 1} :
          Set (PairRing R (Fin 2))) := by
    rwa [← diagonalIdeal_fin_two_eq_span_pair]
  have hmem :=
    secantDet_mul_diagonalIdeal_mem_collisionIdeal
      d₀.first d₀.second d₁.first d₁.second
      (diagonalGenerator (R := R) 0)
      (diagonalGenerator (R := R) 1)
      z hz'
  have hzero :
      d₀.first * diagonalGenerator (R := R) 0 +
          d₀.second * diagonalGenerator (R := R) 1 =
        collisionGenerator F 0 := by
    exact d₀.equation.symm
  have hone :
      d₁.first * diagonalGenerator (R := R) 0 +
          d₁.second * diagonalGenerator (R := R) 1 =
        collisionGenerator F 1 := by
    exact d₁.equation.symm
  rw [hzero, hone] at hmem
  apply
    (show
      Ideal.span
          ({collisionGenerator F 0, collisionGenerator F 1} :
            Set (PairRing R (Fin 2))) ≤
        collisionIdeal F from ?_)
    hmem
  rw [Ideal.span_le]
  intro x hx
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
  rcases hx with rfl | rfl
  · exact Ideal.subset_span (Set.mem_range_self 0)
  · exact Ideal.subset_span (Set.mem_range_self 1)

/-- Fix a secant decomposition for each planar polynomial. -/
noncomputable def planarSecantData
    (p : SourceRing R (Fin 2)) :
    PlanarSecantData p :=
  Classical.choice (nonempty_planarSecantData p)

/-- The determinant of the chosen planar secant matrix. -/
noncomputable def planarSecantDet
    (F : Fin 2 → SourceRing R (Fin 2)) :
    PairRing R (Fin 2) :=
  secantDet
    (planarSecantData (F 0)).first
    (planarSecantData (F 0)).second
    (planarSecantData (F 1)).first
    (planarSecantData (F 1)).second

/-- The chosen secant determinant restricts to the formal Jacobian determinant. -/
theorem diagonalEval_planarSecantDet
    (F : Fin 2 → SourceRing R (Fin 2)) :
    diagonalEval (planarSecantDet F) =
      pderiv 0 (F 0) * pderiv 1 (F 1) -
        pderiv 1 (F 0) * pderiv 0 (F 1) := by
  simp only [planarSecantDet, secantDet, map_sub, map_mul,
    (planarSecantData (F 0)).diagonal_first,
    (planarSecantData (F 0)).diagonal_second,
    (planarSecantData (F 1)).diagonal_first,
    (planarSecantData (F 1)).diagonal_second]

/-- The chosen planar secant determinant annihilates `I_Δ / I_R`. -/
theorem planarSecantDet_mul_diagonalIdeal_mem_collisionIdeal
    (F : Fin 2 → SourceRing R (Fin 2))
    (z : PairRing R (Fin 2))
    (hz : z ∈ diagonalIdeal (R := R) (ι := Fin 2)) :
    planarSecantDet F * z ∈ collisionIdeal F := by
  exact
    secantDataDet_mul_diagonalIdeal_mem_collisionIdeal
      F (planarSecantData (F 0)) (planarSecantData (F 1)) z hz

/-- Over `ℂ`, the diagonal value of the chosen secant determinant is `planarJacobianDet`. -/
theorem diagonalEval_planarSecantDet_eq_planarJacobianDet
    (F : PlanarPolynomialMap) :
    diagonalEval (planarSecantDet F) =
      planarJacobianDet F := by
  simpa only [planarJacobianDet, jacobianDet_fin_two] using
    diagonalEval_planarSecantDet F

/--
For a constant planar Jacobian `c`, the secant determinant is congruent to
the constant polynomial `c` modulo the diagonal ideal.
-/
theorem planarSecantDet_sub_constant_mem_diagonalIdeal
    (F : PlanarPolynomialMap)
    (c : ℂ)
    (hJacobian : planarJacobianDet F = C c) :
    planarSecantDet F - C c ∈
      diagonalIdeal (R := ℂ) (ι := Fin 2) := by
  rw [← diagonalEval_ker]
  change diagonalEval (planarSecantDet F - C c) = 0
  rw [map_sub, diagonalEval_planarSecantDet_eq_planarJacobianDet,
    hJacobian]
  simp [diagonalEval]

private noncomputable def pairConstantUnit
    (c : ℂ) (hc : c ≠ 0) :
    (PairRing ℂ (Fin 2))ˣ :=
  Units.map MvPolynomial.C.toMonoidHom (Units.mk0 c hc)

@[simp]
private theorem pairConstantUnit_val
    (c : ℂ) (hc : c ≠ 0) :
    (pairConstantUnit c hc : PairRing ℂ (Fin 2)) = C c := by
  rfl

/-- The collision equations together with the planar secant determinant. -/
noncomputable def planarSecantIdeal
    (F : PlanarPolynomialMap) :
    Ideal (PairRing ℂ (Fin 2)) :=
  collisionIdeal F ⊔ Ideal.span {planarSecantDet F}

/--
For a planar Keller map, the canonical off-diagonal colon ideal is the
collision ideal together with the chosen secant determinant.
-/
theorem collisionOffDiagonalIdeal_eq_planarSecantIdeal
    (F : PlanarPolynomialMap)
    (hKeller : IsPlanarKeller F) :
    collisionOffDiagonalIdeal F =
      planarSecantIdeal F := by
  obtain ⟨c, hc, hJacobian⟩ := hKeller
  rw [collisionOffDiagonalIdeal, offDiagonalColonIdeal,
    planarSecantIdeal]
  apply colon_eq_sup_span_singleton_of_secant
    (collisionIdeal F)
    (diagonalIdeal (R := ℂ) (ι := Fin 2))
    (planarSecantDet F)
    (pairConstantUnit c hc)
  · exact planarSecantDet_mul_diagonalIdeal_mem_collisionIdeal F
  · simpa using
      planarSecantDet_sub_constant_mem_diagonalIdeal
        F c hJacobian

/--
For a planar Keller map, equality of the collision and diagonal ideals is
equivalent to the concrete secant ideal being the unit ideal.
-/
theorem collisionIdeal_eq_diagonalIdeal_iff_planarSecantIdeal_eq_top
    (F : PlanarPolynomialMap)
    (hKeller : IsPlanarKeller F) :
    collisionIdeal F =
        diagonalIdeal (R := ℂ) (ι := Fin 2) ↔
      planarSecantIdeal F = ⊤ := by
  obtain ⟨c, hc, hJacobian⟩ := hKeller
  rw [planarSecantIdeal]
  apply ideal_eq_iff_sup_span_singleton_eq_top_of_secant
    (collisionIdeal F)
    (diagonalIdeal (R := ℂ) (ι := Fin 2))
    (planarSecantDet F)
    (pairConstantUnit c hc)
    (collisionIdeal_le_diagonalIdeal F)
  · exact planarSecantDet_mul_diagonalIdeal_mem_collisionIdeal F
  · simpa using
      planarSecantDet_sub_constant_mem_diagonalIdeal
        F c hJacobian

/--
For a planar Keller map, the obstruction vanishes exactly when the concrete
secant ideal is the unit ideal.
-/
theorem obstructionIdeal_eq_bot_iff_planarSecantIdeal_eq_top
    (F : PlanarPolynomialMap)
    (hKeller : IsPlanarKeller F) :
    obstructionIdeal F = ⊥ ↔
      planarSecantIdeal F = ⊤ := by
  exact
    (obstructionIdeal_eq_bot_iff F).trans
      (collisionIdeal_eq_diagonalIdeal_iff_planarSecantIdeal_eq_top
        F hKeller)

private noncomputable def collisionConstantUnit
    (F : PlanarPolynomialMap)
    (c : ℂ) (hc : c ≠ 0) :
    (CollisionRing F)ˣ :=
  Units.map
    (Ideal.Quotient.mk (collisionIdeal F)).toMonoidHom
    (pairConstantUnit c hc)

@[simp]
private theorem collisionConstantUnit_val
    (F : PlanarPolynomialMap)
    (c : ℂ) (hc : c ≠ 0) :
    (collisionConstantUnit F c hc : CollisionRing F) =
      Ideal.Quotient.mk (collisionIdeal F) (C c) := by
  rfl

/--
A planar Keller map supplies an explicit idempotent generator of its
off-diagonal obstruction in the collision ring.
-/
theorem exists_collisionOffDiagonalProjector_of_isPlanarKeller
    (F : PlanarPolynomialMap)
    (hKeller : IsPlanarKeller F) :
    ∃ q : CollisionRing F,
      IsCollisionOffDiagonalProjector F q := by
  obtain ⟨c, hc, hJacobian⟩ := hKeller
  let δbar : CollisionRing F :=
    Ideal.Quotient.mk (collisionIdeal F) (planarSecantDet F)
  let cbar : (CollisionRing F)ˣ :=
    collisionConstantUnit F c hc
  have hδann :
      δbar ∈ (obstructionIdeal F).annihilator := by
    exact
      quotient_mk_mem_annihilator_obstruction
        (collisionIdeal F)
        (diagonalIdeal (R := ℂ) (ι := Fin 2))
        (planarSecantDet F)
        (planarSecantDet_mul_diagonalIdeal_mem_collisionIdeal F)
  have hann :
      ∀ j ∈ obstructionIdeal F, δbar * j = 0 := by
    intro j hj
    exact Submodule.mem_annihilator.mp hδann j hj
  have hmod :
      δbar - (cbar : CollisionRing F) ∈
        obstructionIdeal F := by
    have hsource :=
      planarSecantDet_sub_constant_mem_diagonalIdeal
        F c hJacobian
    exact
      Ideal.mem_map_of_mem
        (Ideal.Quotient.mk (collisionIdeal F)) hsource
  refine
    ⟨offDiagonalIdempotent δbar cbar,
      offDiagonalIdempotent_isIdempotent
        (obstructionIdeal F) δbar cbar hann hmod,
      ?_⟩
  exact
    ideal_eq_span_offDiagonalIdempotent
      (obstructionIdeal F) δbar cbar hann hmod

/--
For a planar Keller map, the conventional saturation `I_R : I_Δ^∞` is the
same concrete secant ideal `I_R + (δ_F)`.
-/
theorem collisionIdealSaturation_eq_planarSecantIdeal
    (F : PlanarPolynomialMap)
    (hKeller : IsPlanarKeller F) :
    collisionIdealSaturation F =
      planarSecantIdeal F := by
  obtain ⟨q, hq⟩ :=
    exists_collisionOffDiagonalProjector_of_isPlanarKeller F hKeller
  exact
    (collisionIdealSaturation_eq_collisionOffDiagonalIdeal F q hq).trans
      (collisionOffDiagonalIdeal_eq_planarSecantIdeal F hKeller)

end

end CollisionIdeals
