import CollisionIdeals.General.Collision.Ideal
import Mathlib.RingTheory.Ideal.Colon
import Mathlib.RingTheory.Ideal.Quotient.Operations

set_option autoImplicit false
set_option maxHeartbeats 800000

namespace CollisionIdeals

noncomputable section

universe u

variable {A : Type u} [CommRing A]

/-- The residual ideal left after removing `J` from `V(I)`. -/
def offDiagonalColonIdeal (I J : Ideal A) : Ideal A :=
  I.colon J

/--
The usual ideal saturation `I : J^∞`, indexed by strictly positive
powers of `J`.
-/
def idealSaturation (I J : Ideal A) : Ideal A :=
  ⨆ n : ℕ, I.colon ((J ^ (n + 1) : Ideal A) : Set A)

/--
The pullback of the annihilator of `J/I` is the colon ideal `I : J`.
-/
theorem comap_annihilator_map_quotient_eq_colon
    (I J : Ideal A) :
    ((J.map (Ideal.Quotient.mk I)).annihilator).comap
        (Ideal.Quotient.mk I) =
      I.colon J := by
  ext x
  constructor
  · intro hx
    rw [Submodule.mem_colon]
    intro j hj
    have hzero :
        Ideal.Quotient.mk I x *
            Ideal.Quotient.mk I j = 0 := by
      exact
        Submodule.mem_annihilator.mp hx _
          (Ideal.mem_map_of_mem (Ideal.Quotient.mk I) hj)
    rw [← map_mul, Ideal.Quotient.eq_zero_iff_mem] at hzero
    exact hzero
  · intro hx
    apply Submodule.mem_annihilator.mpr
    intro z hz
    obtain ⟨j, hj, rfl⟩ :=
      (Ideal.mem_map_iff_of_surjective
        (Ideal.Quotient.mk I)
        Ideal.Quotient.mk_surjective).mp hz
    change
      Ideal.Quotient.mk I x *
          Ideal.Quotient.mk I j = 0
    rw [← map_mul, Ideal.Quotient.eq_zero_iff_mem]
    exact Submodule.mem_colon.mp hx j hj

/-- The annihilator of an idempotent summand is its complementary summand. -/
theorem annihilator_span_idempotent
    {q : A} (hq : IsIdempotentElem q) :
    (Ideal.span {q}).annihilator =
      Ideal.span {1 - q} := by
  apply le_antisymm
  · intro x hx
    rw [Ideal.mem_span_singleton']
    refine ⟨x, ?_⟩
    have hxq : x * q = 0 :=
      Submodule.mem_annihilator.mp hx q
        (Ideal.mem_span_singleton_self q)
    rw [mul_sub, mul_one, hxq, sub_zero]
  · intro x hx
    rw [Ideal.mem_span_singleton'] at hx
    obtain ⟨a, rfl⟩ := hx
    apply Submodule.mem_annihilator.mpr
    intro y hy
    rw [Ideal.mem_span_singleton'] at hy
    obtain ⟨b, rfl⟩ := hy
    change (a * (1 - q)) * (b * q) = 0
    rw [show (a * (1 - q)) * (b * q) =
      (a * b) * ((1 - q) * q) by ring]
    rw [sub_mul, one_mul, hq.eq, sub_self, mul_zero]

/-- An idempotent is determined by the principal ideal that it generates. -/
theorem idempotent_eq_of_span_singleton_eq
    {p q : A}
    (hp : IsIdempotentElem p)
    (hq : IsIdempotentElem q)
    (hspan : Ideal.span {p} = Ideal.span {q}) :
    p = q := by
  have hpq_eq_p : p * q = p := by
    have hp_mem : p ∈ Ideal.span {q} := by
      rw [← hspan]
      exact Ideal.mem_span_singleton_self p
    rw [Ideal.mem_span_singleton'] at hp_mem
    obtain ⟨a, rfl⟩ := hp_mem
    rw [mul_assoc, hq.eq]
  have hpq_eq_q : p * q = q := by
    have hq_mem : q ∈ Ideal.span {p} := by
      rw [hspan]
      exact Ideal.mem_span_singleton_self q
    rw [Ideal.mem_span_singleton'] at hq_mem
    obtain ⟨b, rfl⟩ := hq_mem
    calc
      p * (b * p) = b * (p * p) := by ring
      _ = b * p := by rw [hp.eq]
  exact hpq_eq_p.symm.trans hpq_eq_q

theorem span_idempotent_inf_span_one_sub_eq_bot
    {q : A} (hq : IsIdempotentElem q) :
    Ideal.span {q} ⊓ Ideal.span {1 - q} = ⊥ := by
  rw [← annihilator_span_idempotent hq]
  apply le_bot_iff.mp
  intro x hx
  have hxq : x * q = 0 :=
    Submodule.mem_annihilator.mp hx.2 q
      (Ideal.mem_span_singleton_self q)
  obtain ⟨a, rfl⟩ :=
    Ideal.mem_span_singleton'.mp hx.1
  rw [Ideal.mem_bot]
  simpa [mul_assoc, hq.eq] using hxq

theorem span_idempotent_sup_span_one_sub_eq_top
    (q : A) :
    Ideal.span {q} ⊔ Ideal.span {1 - q} = ⊤ := by
  rw [Ideal.eq_top_iff_one]
  have hq : q ∈ Ideal.span {q} ⊔ Ideal.span {1 - q} :=
    le_sup_left (a := Ideal.span {q})
      (b := Ideal.span {1 - q})
      (Ideal.mem_span_singleton_self q)
  have ht : 1 - q ∈ Ideal.span {q} ⊔ Ideal.span {1 - q} :=
    le_sup_right (a := Ideal.span {q})
      (b := Ideal.span {1 - q})
      (Ideal.mem_span_singleton_self (1 - q))
  have := (Ideal.span {q} ⊔ Ideal.span {1 - q}).add_mem hq ht
  simpa using this

/--
The image of `J` modulo `I` is generated by an idempotent.  This is the
algebraic form of `V(J/I)` being open and closed in `Spec(A/I)`.
-/
def IsClopenModulo
    (I J : Ideal A) (projector : A ⧸ I) : Prop :=
  I ≤ J ∧
  IsIdempotentElem projector ∧
    J.map (Ideal.Quotient.mk I) =
      Ideal.span {projector}

/-- For a clopen summand, every positive colon power equals the first one. -/
theorem colon_power_eq_colon_of_isClopenModulo
    (I J : Ideal A) (q : A ⧸ I)
    (h : IsClopenModulo I J q)
    (n : ℕ) :
    I.colon ((J ^ (n + 1) : Ideal A) : Set A) = I.colon J := by
  rw [← comap_annihilator_map_quotient_eq_colon I (J ^ (n + 1)),
    Ideal.map_pow, h.2.2, Ideal.span_singleton_pow,
    h.2.1.pow_eq (Nat.succ_ne_zero n),
    ← h.2.2,
    comap_annihilator_map_quotient_eq_colon I J]

/-- Clopenness makes the infinite saturation stabilize at the first colon. -/
theorem idealSaturation_eq_offDiagonalColonIdeal
    (I J : Ideal A) (q : A ⧸ I)
    (h : IsClopenModulo I J q) :
    idealSaturation I J = offDiagonalColonIdeal I J := by
  simp only [idealSaturation,
    colon_power_eq_colon_of_isClopenModulo I J q h,
    iSup_const, offDiagonalColonIdeal]

/-- The residual colon ideal is the pullback of the complementary projector. -/
theorem offDiagonalColonIdeal_eq_comap_complement
    (I J : Ideal A) (q : A ⧸ I)
    (h : IsClopenModulo I J q) :
    offDiagonalColonIdeal I J =
      (Ideal.span {1 - q}).comap
        (Ideal.Quotient.mk I) := by
  rw [offDiagonalColonIdeal,
    ← comap_annihilator_map_quotient_eq_colon I J,
    h.2.2,
    annihilator_span_idempotent h.2.1]

/-- A clopen ideal and its residual complement intersect in the base ideal. -/
theorem inf_offDiagonalColonIdeal_eq
    (I J : Ideal A) (q : A ⧸ I)
    (h : IsClopenModulo I J q) :
    J ⊓ offDiagonalColonIdeal I J = I := by
  let π := Ideal.Quotient.mk I
  have hJ :
      (Ideal.span {q}).comap π = J := by
    rw [← h.2.2,
      Ideal.comap_map_of_surjective
        π Ideal.Quotient.mk_surjective J]
    change J ⊔ RingHom.ker π = J
    apply sup_eq_left.mpr
    simpa [π, Ideal.mk_ker] using h.1
  rw [offDiagonalColonIdeal_eq_comap_complement I J q h,
    ← hJ, ← Ideal.comap_inf,
    span_idempotent_inf_span_one_sub_eq_bot h.2.1,
    ← RingHom.ker_eq_comap_bot, Ideal.mk_ker]

/-- A clopen ideal and its residual complement are comaximal. -/
theorem sup_offDiagonalColonIdeal_eq_top
    (I J : Ideal A) (q : A ⧸ I)
    (h : IsClopenModulo I J q) :
    J ⊔ offDiagonalColonIdeal I J = ⊤ := by
  let π := Ideal.Quotient.mk I
  have hker :
      RingHom.ker π ≤ J ⊔ offDiagonalColonIdeal I J := by
    rw [Ideal.mk_ker]
    exact h.1.trans le_sup_left
  calc
    J ⊔ offDiagonalColonIdeal I J =
        ((J ⊔ offDiagonalColonIdeal I J).map π).comap π := by
          rw [Ideal.comap_map_of_surjective
              π Ideal.Quotient.mk_surjective]
          change
            J ⊔ offDiagonalColonIdeal I J =
              (J ⊔ offDiagonalColonIdeal I J) ⊔
                RingHom.ker π
          exact (sup_eq_left.mpr hker).symm
    _ = (Ideal.span {q} ⊔
          Ideal.span {1 - q}).comap π := by
          rw [Ideal.map_sup, h.2.2,
            offDiagonalColonIdeal_eq_comap_complement I J q h,
            Ideal.map_comap_of_surjective
              π Ideal.Quotient.mk_surjective]
    _ = ⊤ := by
          rw [span_idempotent_sup_span_one_sub_eq_top,
            Ideal.comap_top]

/--
There is a single element equal to `1` along `V(J)` that annihilates `J`
modulo `I`.  Localizing at this element makes `I` and `J` equal.
-/
theorem exists_neighborhood_element_of_isClopenModulo
    (I J : Ideal A) (q : A ⧸ I)
    (h : IsClopenModulo I J q) :
    ∃ s : A,
      s - 1 ∈ J ∧
        ∀ j ∈ J, s * j ∈ I := by
  let π := Ideal.Quotient.mk I
  have hqmap :
      q ∈ J.map π := by
    rw [h.2.2]
    exact Ideal.mem_span_singleton_self q
  obtain ⟨j, hj, hjq⟩ :=
    (Ideal.mem_map_iff_of_surjective
      π Ideal.Quotient.mk_surjective).mp hqmap
  refine ⟨1 - j, ?_, ?_⟩
  · simpa [sub_eq_add_neg, add_assoc] using J.neg_mem hj
  · intro z hz
    apply
      Submodule.mem_colon.mp
        (show 1 - j ∈ I.colon J from ?_) z hz
    rw [← offDiagonalColonIdeal,
      offDiagonalColonIdeal_eq_comap_complement I J q h]
    change π (1 - j) ∈ Ideal.span {1 - q}
    rw [map_sub, map_one, hjq]
    exact Ideal.mem_span_singleton_self (1 - q)

theorem isCoprime_diagonal_offDiagonalColonIdeal
    (I J : Ideal A) (q : A ⧸ I)
    (h : IsClopenModulo I J q) :
    IsCoprime J (offDiagonalColonIdeal I J) := by
  rw [Ideal.isCoprime_iff_sup_eq]
  exact sup_offDiagonalColonIdeal_eq_top I J q h

/-- The Chinese-remainder decomposition associated to a clopen summand. -/
noncomputable def quotientEquivDiagonalProdOffDiagonal
    (I J : Ideal A) (q : A ⧸ I)
    (h : IsClopenModulo I J q) :
    A ⧸ I ≃+*
      (A ⧸ J) × (A ⧸ offDiagonalColonIdeal I J) := by
  let e :=
    Ideal.quotientInfEquivQuotientProd
      J (offDiagonalColonIdeal I J)
      (isCoprime_diagonal_offDiagonalColonIdeal I J q h)
  exact
    (Ideal.quotEquivOfEq
      (inf_offDiagonalColonIdeal_eq I J q h).symm).trans e

section Collision

universe v w

variable {R : Type u} [CommRing R]
variable {ι : Type v} {κ : Type w}

/--
The first-colon residual ideal `I_R(F) : I_Δ`.

Once the collision diagonal is clopen, saturation by `I_Δ` stabilizes at
this ideal and it cuts out the complementary off-diagonal summand.
-/
def collisionOffDiagonalIdeal
    (F : κ → SourceRing R ι) :
    Ideal (PairRing R ι) :=
  offDiagonalColonIdeal
    (collisionIdeal F)
    (diagonalIdeal (R := R) (ι := ι))

/--
The coordinate ring of the first-colon residual scheme. When the collision
diagonal is clopen, this is the complementary off-diagonal factor.
-/
abbrev OffDiagonalRing
    (F : κ → SourceRing R ι) :=
  PairRing R ι ⧸ collisionOffDiagonalIdeal F

/-- The collision ideal is contained in its first-colon residual ideal. -/
theorem collisionIdeal_le_collisionOffDiagonalIdeal
    (F : κ → SourceRing R ι) :
    collisionIdeal F ≤ collisionOffDiagonalIdeal F := by
  exact Ideal.le_colon

/--
The canonical quotient from the collision ring to its first-colon
off-diagonal ring.
-/
def collisionToOffDiagonal
    (F : κ → SourceRing R ι) :
    CollisionRing F →ₐ[R] OffDiagonalRing F :=
  Ideal.Quotient.factorₐ R
    (collisionIdeal_le_collisionOffDiagonalIdeal F)

/-- The collision-to-off-diagonal quotient agrees with the direct quotient
on the ambient pair ring. -/
@[simp]
theorem collisionToOffDiagonal_comp_quotient
    (F : κ → SourceRing R ι) :
    (collisionToOffDiagonal F).comp
        (Ideal.Quotient.mkₐ R (collisionIdeal F)) =
      Ideal.Quotient.mkₐ R (collisionOffDiagonalIdeal F) := by
  rfl

/-- The conventional saturation `I_R(F) : I_Δ^∞`. -/
def collisionIdealSaturation
    (F : κ → SourceRing R ι) :
    Ideal (PairRing R ι) :=
  idealSaturation
    (collisionIdeal F)
    (diagonalIdeal (R := R) (ι := ι))

/--
An explicit off-diagonal projector for the collision ring.  This is the
algebraic datum supplied by the diagonal being open and closed.
-/
def IsCollisionOffDiagonalProjector
    (F : κ → SourceRing R ι)
    (q : CollisionRing F) : Prop :=
  IsIdempotentElem q ∧
    obstructionIdeal F = Ideal.span {q}

/-- The off-diagonal collision projector is unique when it exists. -/
theorem collisionOffDiagonalProjector_unique
    (F : κ → SourceRing R ι)
    {q r : CollisionRing F}
    (hq : IsCollisionOffDiagonalProjector F q)
    (hr : IsCollisionOffDiagonalProjector F r) :
    q = r :=
  idempotent_eq_of_span_singleton_eq
    hq.1 hr.1 (hq.2.symm.trans hr.2)

theorem isClopenModulo_of_collisionOffDiagonalProjector
    (F : κ → SourceRing R ι)
    (q : CollisionRing F)
    (hq : IsCollisionOffDiagonalProjector F q) :
    IsClopenModulo
      (collisionIdeal F)
      (diagonalIdeal (R := R) (ι := ι))
      q := by
  refine ⟨collisionIdeal_le_diagonalIdeal F, hq.1, ?_⟩
  exact hq.2

/-- For a clopen collision diagonal, `I_R : I_Δ^∞ = I_R : I_Δ`. -/
theorem collisionIdealSaturation_eq_collisionOffDiagonalIdeal
    (F : κ → SourceRing R ι)
    (q : CollisionRing F)
    (hq : IsCollisionOffDiagonalProjector F q) :
    collisionIdealSaturation F =
      collisionOffDiagonalIdeal F := by
  exact
    idealSaturation_eq_offDiagonalColonIdeal
      (collisionIdeal F)
      (diagonalIdeal (R := R) (ι := ι))
      q
      (isClopenModulo_of_collisionOffDiagonalProjector F q hq)

theorem collisionIdeal_eq_diagonalIdeal_inf_collisionOffDiagonalIdeal
    (F : κ → SourceRing R ι)
    (q : CollisionRing F)
    (hq : IsCollisionOffDiagonalProjector F q) :
    collisionIdeal F =
      diagonalIdeal (R := R) (ι := ι) ⊓
        collisionOffDiagonalIdeal F := by
  exact
    (inf_offDiagonalColonIdeal_eq
      (collisionIdeal F)
      (diagonalIdeal (R := R) (ι := ι))
      q
      (isClopenModulo_of_collisionOffDiagonalProjector F q hq)).symm

theorem diagonal_sup_collisionOffDiagonalIdeal_eq_top
    (F : κ → SourceRing R ι)
    (q : CollisionRing F)
    (hq : IsCollisionOffDiagonalProjector F q) :
    diagonalIdeal (R := R) (ι := ι) ⊔
      collisionOffDiagonalIdeal F = ⊤ := by
  exact
    sup_offDiagonalColonIdeal_eq_top
      (collisionIdeal F)
      (diagonalIdeal (R := R) (ι := ι))
      q
      (isClopenModulo_of_collisionOffDiagonalProjector F q hq)

/--
There is an `h ≡ 1 mod I_Δ` with `h I_Δ ⊆ I_R`; hence `I_R` and
`I_Δ` agree on the principal neighborhood selected by `h`.
-/
theorem exists_collision_diagonal_neighborhood_element
    (F : κ → SourceRing R ι)
    (q : CollisionRing F)
    (hq : IsCollisionOffDiagonalProjector F q) :
    ∃ h : PairRing R ι,
      h - 1 ∈ diagonalIdeal (R := R) (ι := ι) ∧
        ∀ z ∈ diagonalIdeal (R := R) (ι := ι),
          h * z ∈ collisionIdeal F := by
  exact
    exists_neighborhood_element_of_isClopenModulo
      (collisionIdeal F)
      (diagonalIdeal (R := R) (ι := ι))
      q
      (isClopenModulo_of_collisionOffDiagonalProjector F q hq)

/-- The collision ring splits into its diagonal and off-diagonal factors. -/
noncomputable def collisionRingEquivDiagonalProdOffDiagonal
    (F : κ → SourceRing R ι)
    (q : CollisionRing F)
    (hq : IsCollisionOffDiagonalProjector F q) :
    CollisionRing F ≃+*
      (PairRing R ι ⧸ diagonalIdeal (R := R) (ι := ι)) ×
      (PairRing R ι ⧸ collisionOffDiagonalIdeal F) :=
  quotientEquivDiagonalProdOffDiagonal
    (collisionIdeal F)
    (diagonalIdeal (R := R) (ι := ι))
    q
    (isClopenModulo_of_collisionOffDiagonalProjector F q hq)

/-- The obstruction vanishes exactly when the off-diagonal ideal is the unit ideal. -/
theorem obstructionIdeal_eq_bot_iff_collisionOffDiagonalIdeal_eq_top
    (F : κ → SourceRing R ι) :
    obstructionIdeal F = ⊥ ↔
      collisionOffDiagonalIdeal F = ⊤ := by
  rw [obstructionIdeal_eq_bot_iff]
  constructor
  · intro h
    rw [collisionOffDiagonalIdeal, offDiagonalColonIdeal,
      h, Ideal.eq_top_iff_one]
    apply Submodule.mem_colon.mpr
    intro x hx
    simpa using hx
  · intro h
    apply le_antisymm (collisionIdeal_le_diagonalIdeal F)
    intro x hx
    rw [collisionOffDiagonalIdeal, offDiagonalColonIdeal,
      Ideal.eq_top_iff_one] at h
    have hx' := Submodule.mem_colon.mp h x hx
    simpa using hx'

/-- Equivalently, the off-diagonal quotient ring is the zero ring. -/
theorem obstructionIdeal_eq_bot_iff_offDiagonalRing_subsingleton
    (F : κ → SourceRing R ι) :
    obstructionIdeal F = ⊥ ↔
      Subsingleton
        (OffDiagonalRing F) := by
  rw [Ideal.Quotient.subsingleton_iff]
  exact
    obstructionIdeal_eq_bot_iff_collisionOffDiagonalIdeal_eq_top
      F

/--
A collision off-diagonal projector vanishes exactly when the obstruction
ideal vanishes.
-/
theorem collisionOffDiagonalProjector_eq_zero_iff_obstructionIdeal_eq_bot
    (F : κ → SourceRing R ι)
    (q : CollisionRing F)
    (hq : IsCollisionOffDiagonalProjector F q) :
    q = 0 ↔ obstructionIdeal F = ⊥ := by
  rw [hq.2, Ideal.span_singleton_eq_bot]

/--
A collision off-diagonal projector vanishes exactly when the collision and
diagonal ideals agree.
-/
theorem collisionOffDiagonalProjector_eq_zero_iff_collisionIdeal_eq_diagonalIdeal
    (F : κ → SourceRing R ι)
    (q : CollisionRing F)
    (hq : IsCollisionOffDiagonalProjector F q) :
    q = 0 ↔
      collisionIdeal F =
        diagonalIdeal (R := R) (ι := ι) :=
  (collisionOffDiagonalProjector_eq_zero_iff_obstructionIdeal_eq_bot
      F q hq).trans
    (obstructionIdeal_eq_bot_iff F)

/--
A collision off-diagonal projector is nonzero exactly when the collision
ideal differs from the diagonal ideal.
-/
theorem collisionOffDiagonalProjector_ne_zero_iff_collisionIdeal_ne_diagonalIdeal
    (F : κ → SourceRing R ι)
    (q : CollisionRing F)
    (hq : IsCollisionOffDiagonalProjector F q) :
    q ≠ 0 ↔
      collisionIdeal F ≠
        diagonalIdeal (R := R) (ι := ι) :=
  not_congr
    (collisionOffDiagonalProjector_eq_zero_iff_collisionIdeal_eq_diagonalIdeal
      F q hq)

/--
Since the collision ideal is always contained in the diagonal ideal, a
collision off-diagonal projector is nonzero exactly when that containment is
strict.
-/
theorem collisionOffDiagonalProjector_ne_zero_iff_collisionIdeal_lt_diagonalIdeal
    (F : κ → SourceRing R ι)
    (q : CollisionRing F)
    (hq : IsCollisionOffDiagonalProjector F q) :
    q ≠ 0 ↔
      collisionIdeal F <
        diagonalIdeal (R := R) (ι := ι) := by
  rw [collisionOffDiagonalProjector_ne_zero_iff_collisionIdeal_ne_diagonalIdeal
      F q hq,
    lt_iff_le_and_ne]
  exact
    ⟨fun h ↦ ⟨collisionIdeal_le_diagonalIdeal F, h⟩,
      fun h ↦ h.2⟩

/--
A collision off-diagonal projector is nonzero exactly when its complementary
off-diagonal factor is a nontrivial ring.
-/
theorem collisionOffDiagonalProjector_ne_zero_iff_offDiagonalRing_nontrivial
    (F : κ → SourceRing R ι)
    (q : CollisionRing F)
    (hq : IsCollisionOffDiagonalProjector F q) :
    q ≠ 0 ↔ Nontrivial (OffDiagonalRing F) := by
  exact
    (not_congr
      (collisionOffDiagonalProjector_eq_zero_iff_obstructionIdeal_eq_bot
        F q hq)).trans
      ((not_congr
        (obstructionIdeal_eq_bot_iff_offDiagonalRing_subsingleton F)).trans
        not_subsingleton_iff_nontrivial)

end Collision

end

end CollisionIdeals
