import Mathlib.Algebra.MvPolynomial.Monad
import Mathlib.Algebra.MvPolynomial.PDeriv
import Mathlib.Algebra.MvPolynomial.Rename
import Mathlib.Data.Complex.Basic
import Mathlib.Data.Fintype.EquivFin
import Mathlib.FieldTheory.Normal.Closure
import Mathlib.LinearAlgebra.Matrix.Determinant.Basic
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.RingTheory.Localization.FractionRing
import Mathlib.RingTheory.TensorProduct.Basic

/-!
# Generic cubic collisions in complex dimension three

This is the small, Mathlib-only statement surface for the principal result
of Paper I.  All geometric objects occurring in the theorem are defined
directly below.  The result is explicitly conditional on the classical
Keller--Galois rigidity theorem.
-/

set_option autoImplicit false

namespace CollisionIdeals.Palomar.PaperOne

noncomputable section

open MvPolynomial
open scoped TensorProduct

/-- The coordinate ring of complex affine three-space. -/
abbrev SourceRing := MvPolynomial (Fin 3) ℂ

/-- The coordinate ring of two labelled copies of complex affine three-space. -/
abbrev PairRing := MvPolynomial (Sum (Fin 3) (Fin 3)) ℂ

/-- A polynomial self-map of complex affine three-space. -/
abbrev PolynomialMap := Fin 3 → SourceRing

/-- Put a source polynomial in the left set of variables. -/
def leftRename : SourceRing →ₐ[ℂ] PairRing :=
  MvPolynomial.rename Sum.inl

/-- Put a source polynomial in the right set of variables. -/
def rightRename : SourceRing →ₐ[ℂ] PairRing :=
  MvPolynomial.rename Sum.inr

/-- The ideal generated by the equations `Fᵢ(x) - Fᵢ(y)`. -/
def collisionIdeal (F : PolynomialMap) : Ideal PairRing :=
  Ideal.span (Set.range fun i ↦ leftRename (F i) - rightRename (F i))

/-- The coordinate ring of the collision scheme of `F`. -/
abbrev CollisionRing (F : PolynomialMap) :=
  PairRing ⧸ collisionIdeal F

/-- The ideal generated by the equations `xᵢ - yᵢ`. -/
def diagonalIdeal : Ideal PairRing :=
  Ideal.span (Set.range fun i : Fin 3 ↦
    (X (Sum.inl i) : PairRing) - X (Sum.inr i))

/-- The image of the diagonal ideal in the collision ring. -/
def obstructionIdeal (F : PolynomialMap) : Ideal (CollisionRing F) :=
  diagonalIdeal.map (Ideal.Quotient.mk (collisionIdeal F))

/-- The left source map into the collision ring. -/
def collisionLeft (F : PolynomialMap) : SourceRing →ₐ[ℂ] CollisionRing F :=
  (Ideal.Quotient.mkₐ ℂ (collisionIdeal F)).comp leftRename

/-- Restriction to the diagonal `x = y`. -/
def diagonalEval : PairRing →ₐ[ℂ] SourceRing :=
  MvPolynomial.rename (Sum.elim id id)

theorem collisionIdeal_le_diagonalEval_ker (F : PolynomialMap) :
    collisionIdeal F ≤ RingHom.ker diagonalEval.toRingHom := by
  rw [collisionIdeal, Ideal.span_le]
  rintro _ ⟨i, rfl⟩
  change diagonalEval (leftRename (F i) - rightRename (F i)) = 0
  simp [diagonalEval, leftRename, rightRename, MvPolynomial.rename_rename]

/-- Diagonal evaluation descended to the collision quotient. -/
def collisionDiagonal (F : PolynomialMap) :
    CollisionRing F →ₐ[ℂ] SourceRing :=
  Ideal.Quotient.liftₐ
    (collisionIdeal F) diagonalEval (collisionIdeal_le_diagonalEval_ker F)

@[simp]
theorem collisionDiagonal_collisionLeft (F : PolynomialMap) (a : SourceRing) :
    collisionDiagonal F (collisionLeft F a) = a := by
  simp [collisionDiagonal, collisionLeft, diagonalEval, leftRename,
    MvPolynomial.rename_rename]

/-- Substitution by the coordinate polynomials of `F`. -/
def coordinateAlgHom (F : PolynomialMap) :
    MvPolynomial (Fin 3) ℂ →ₐ[ℂ] SourceRing :=
  MvPolynomial.aeval F

/-- The subalgebra generated by the coordinate polynomials of `F`. -/
def ImageAlgebra (F : PolynomialMap) : Subalgebra ℂ SourceRing :=
  (coordinateAlgHom F).range

/-- The rational function field of the source. -/
abbrev SourceFunctionField := FractionRing SourceRing

/-- The fraction field of the coordinate-image algebra of `F`. -/
abbrev BaseFunctionField (F : PolynomialMap) :=
  FractionRing (ImageAlgebra F)

noncomputable def imageToSourceFunctionField (F : PolynomialMap) :
    ImageAlgebra F →+* SourceFunctionField :=
  (algebraMap SourceRing SourceFunctionField).comp
    (algebraMap (ImageAlgebra F) SourceRing)

theorem imageToSourceFunctionField_injective (F : PolynomialMap) :
    Function.Injective (imageToSourceFunctionField F) :=
  (FaithfulSMul.algebraMap_injective SourceRing SourceFunctionField).comp
    (FaithfulSMul.algebraMap_injective (ImageAlgebra F) SourceRing)

/-- The induced embedding of the base function field in the source field. -/
noncomputable def baseFunctionFieldEmbedding (F : PolynomialMap) :
    BaseFunctionField F →+* SourceFunctionField :=
  IsFractionRing.lift (imageToSourceFunctionField_injective F)

noncomputable instance (F : PolynomialMap) :
    Algebra (BaseFunctionField F) SourceFunctionField :=
  (baseFunctionFieldEmbedding F).toAlgebra

noncomputable instance (F : PolynomialMap) :
    IsScalarTower (ImageAlgebra F) (BaseFunctionField F)
      SourceFunctionField :=
  IsScalarTower.of_algebraMap_eq fun b ↦ by
    exact (IsFractionRing.lift_algebraMap
      (imageToSourceFunctionField_injective F) b).symm

noncomputable instance (F : PolynomialMap) :
    Algebra (ImageAlgebra F) (CollisionRing F) :=
  ((collisionLeft F).comp
    (Subalgebra.val (ImageAlgebra F))).toRingHom.toAlgebra

/-- Diagonal evaluation regarded as a map over the coordinate-image algebra. -/
noncomputable def imageCollisionDiagonal (F : PolynomialMap) :
    CollisionRing F →ₐ[ImageAlgebra F] SourceRing :=
  { toRingHom := (collisionDiagonal F).toRingHom
    commutes' := fun b ↦ by
      change collisionDiagonal F (collisionLeft F b.1) = b.1
      exact collisionDiagonal_collisionLeft F b.1 }

/-- The canonical diagonal map after base change from the image algebra to its
fraction field. -/
noncomputable def genericCollisionDiagonal (F : PolynomialMap) :
    (BaseFunctionField F ⊗[ImageAlgebra F] CollisionRing F) →ₐ[
      BaseFunctionField F] SourceFunctionField := by
  let fK : BaseFunctionField F →ₐ[ImageAlgebra F] SourceFunctionField :=
    IsScalarTower.toAlgHom
      (ImageAlgebra F) (BaseFunctionField F) SourceFunctionField
  let fC : CollisionRing F →ₐ[ImageAlgebra F] SourceFunctionField :=
    (IsScalarTower.toAlgHom
      (ImageAlgebra F) SourceRing SourceFunctionField).comp
        (imageCollisionDiagonal F)
  let fB :
      (BaseFunctionField F ⊗[ImageAlgebra F] CollisionRing F) →ₐ[
        ImageAlgebra F] SourceFunctionField :=
    Algebra.TensorProduct.lift fK fC (fun _ _ ↦ mul_comm _ _)
  exact
    { toRingHom := fB.toRingHom
      commutes' := fun k ↦ by
        change fB (k ⊗ₜ[ImageAlgebra F] (1 : CollisionRing F)) =
          algebraMap (BaseFunctionField F) SourceFunctionField k
        simp [fB, fK] }

/-- The Jacobian determinant of `F` is a nonzero complex constant. -/
def IsKeller (F : PolynomialMap) : Prop :=
  ∃ c : ℂ, c ≠ 0 ∧
    Matrix.det (fun i j : Fin 3 ↦ pderiv j (F i)) = C c

/-- Substitution by `F` is an automorphism of the polynomial ring. -/
def IsPolynomialAutomorphism (F : PolynomialMap) : Prop :=
  Function.Bijective (MvPolynomial.bind₁ F)

/-- A Keller map that is not a polynomial automorphism. -/
def IsJacobianCounterexample (F : PolynomialMap) : Prop :=
  IsKeller F ∧ ¬ IsPolynomialAutomorphism F

/-- Classical Keller--Galois rigidity in complex dimension three. -/
def KellerGaloisRigidity : Prop :=
  ∀ F : PolynomialMap, IsKeller F →
    Normal (BaseFunctionField F) SourceFunctionField →
    IsPolynomialAutomorphism F

/--
Assume Keller--Galois rigidity.  If a complex three-dimensional Keller map
has generic degree three, then its generic collision algebra is the product
of the source function field and any chosen finite normal closure.  The first
projection is the base-changed diagonal evaluation, the normal-closure Galois
group is `S₃`, and the affine collision obstruction is nonzero.
-/
theorem genericDegreeThreeS3Collision
    (hRigidity : KellerGaloisRigidity)
    (F : PolynomialMap)
    (hKeller : IsKeller F)
    (N : Type*) [Field N]
    [Algebra SourceFunctionField N]
    [Algebra (BaseFunctionField F) N]
    [IsScalarTower (BaseFunctionField F) SourceFunctionField N]
    (normalClosure :
      IsNormalClosure (BaseFunctionField F) SourceFunctionField N)
    (finiteNormal : FiniteDimensional (BaseFunctionField F) N)
    (hdegree :
      Module.finrank (BaseFunctionField F) SourceFunctionField = 3) :
    IsJacobianCounterexample F ∧
      obstructionIdeal F ≠ ⊥ ∧
      collisionIdeal F < diagonalIdeal ∧
      ∃ e :
          (BaseFunctionField F ⊗[ImageAlgebra F] CollisionRing F) ≃ₐ[
            BaseFunctionField F] SourceFunctionField × N,
        (AlgHom.fst
            (BaseFunctionField F) SourceFunctionField N).comp e.toAlgHom =
          genericCollisionDiagonal F ∧
        Nonempty
          ((N ≃ₐ[BaseFunctionField F] N) ≃* Equiv.Perm (Fin 3)) := by
  sorry

end

end CollisionIdeals.Palomar.PaperOne
