import Mathlib.Algebra.MvPolynomial.CommRing
import Mathlib.Algebra.MvPolynomial.Monad
import Mathlib.Algebra.MvPolynomial.PDeriv
import Mathlib.Algebra.MvPolynomial.Rename
import Mathlib.Data.Complex.Basic
import Mathlib.FieldTheory.Normal.Basic
import Mathlib.LinearAlgebra.Matrix.Determinant.Basic
import Mathlib.Algebra.Polynomial.Identities
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.RingTheory.Localization.FractionRing
/-!
# Explicit planar secants and quadratic collision rigidity

This Mathlib-only surface exposes the ordered divided-difference collision
projector and the degree-two exclusion from Paper II.  The classical
Keller--Galois rigidity theorem remains an explicit hypothesis.

It is not asserted as an axiom or proved by this challenge.
-/
set_option autoImplicit false

namespace CollisionIdeals

open MvPolynomial

noncomputable section

universe u v w

/-- Two labelled copies of the source variables. -/
abbrev PairVars (ι : Type v) := Sum ι ι

/-- The polynomial ring on one copy of affine space. -/
abbrev SourceRing (R : Type u) (ι : Type v) [CommRing R] :=
  MvPolynomial ι R

/-- The polynomial ring on two copies of affine space. -/
abbrev PairRing (R : Type u) (ι : Type v) [CommRing R] :=
  MvPolynomial (PairVars ι) R

/-- Put a polynomial in the left copy of the source variables. -/
def leftRename {R : Type u} [CommRing R] {ι : Type v} :
    SourceRing R ι →ₐ[R] PairRing R ι :=
  MvPolynomial.rename Sum.inl

/-- Put a polynomial in the right copy of the source variables. -/
def rightRename {R : Type u} [CommRing R] {ι : Type v} :
    SourceRing R ι →ₐ[R] PairRing R ι :=
  MvPolynomial.rename Sum.inr

/-- A standard generator `xᵢ(left) - xᵢ(right)` of the diagonal ideal. -/
def diagonalGenerator
    {R : Type u} [CommRing R] {ι : Type v} (i : ι) : PairRing R ι :=
  (X (Sum.inl i : PairVars ι) : PairRing R ι) -
    (X (Sum.inr i : PairVars ι) : PairRing R ι)

/-- The diagonal ideal in the coordinate ring of two copies of affine space. -/
def diagonalIdeal
    {R : Type u} [CommRing R] {ι : Type v} : Ideal (PairRing R ι) :=
  Ideal.span (Set.range (diagonalGenerator (R := R) (ι := ι)))

/-- A collision equation attached to an output coordinate of `F`. -/
def collisionGenerator
    {R : Type u} [CommRing R] {ι : Type v} {κ : Type w}
    (F : κ → SourceRing R ι) (j : κ) : PairRing R ι :=
  leftRename (R := R) (ι := ι) (F j) -
    rightRename (R := R) (ι := ι) (F j)

/-- The collision ideal generated by equality of the two images under `F`. -/
def collisionIdeal
    {R : Type u} [CommRing R] {ι : Type v} {κ : Type w}
    (F : κ → SourceRing R ι) : Ideal (PairRing R ι) :=
  Ideal.span (Set.range (collisionGenerator F))

/-- The coordinate ring of the self-fiber product cut out by the collision ideal. -/
abbrev CollisionRing
    {R : Type u} [CommRing R] {ι : Type v} {κ : Type w}
    (F : κ → SourceRing R ι) :=
  PairRing R ι ⧸ collisionIdeal F

/-- The image of the diagonal ideal in the collision ring. -/
def obstructionIdeal
    {R : Type u} [CommRing R] {ι : Type v} {κ : Type w}
    (F : κ → SourceRing R ι) : Ideal (CollisionRing F) :=
  (diagonalIdeal (R := R) (ι := ι)).map
    (Ideal.Quotient.mk (collisionIdeal F))

/-- The coordinate-ring map determined by the coordinate polynomials `F`. -/
def coordinateAlgHom
    {R : Type u} [CommRing R] {ι : Type v} {κ : Type w}
    (F : κ → SourceRing R ι) :
    MvPolynomial κ R →ₐ[R] SourceRing R ι :=
  MvPolynomial.aeval F

/-- The coordinate algebra generated by the coordinates of `F`. -/
def polynomialMapImageAlgebra
    {R : Type u} [CommRing R] [IsDomain R] {ι κ : Type v}
    (F : κ → SourceRing R ι) : Subalgebra R (SourceRing R ι) :=
  (coordinateAlgHom F).range

/-- The function field of the polynomial source. -/
abbrev PolynomialSourceFunctionField
    {R : Type u} [CommRing R] [IsDomain R] {ι : Type v} :=
  FractionRing (SourceRing R ι)

/-- The function field of the coordinate image algebra. -/
abbrev PolynomialBaseFunctionField
    {R : Type u} [CommRing R] [IsDomain R] {ι κ : Type v}
    (F : κ → SourceRing R ι) :=
  FractionRing (polynomialMapImageAlgebra F)

/-- The inclusion of the image algebra into the source function field. -/
noncomputable def polynomialMapImageAlgebraToFunctionField
    {R : Type u} [CommRing R] [IsDomain R] {ι κ : Type v}
    (F : κ → SourceRing R ι) :
    polynomialMapImageAlgebra F →+*
      PolynomialSourceFunctionField (R := R) (ι := ι) :=
  (algebraMap
      (SourceRing R ι)
      (PolynomialSourceFunctionField (R := R) (ι := ι))).comp
    (algebraMap (polynomialMapImageAlgebra F) (SourceRing R ι))

/-- The image algebra embeds in the source function field. -/
theorem polynomialMapImageAlgebraToFunctionField_injective
    {R : Type u} [CommRing R] [IsDomain R] {ι κ : Type v}
    (F : κ → SourceRing R ι) :
    Function.Injective (polynomialMapImageAlgebraToFunctionField F) :=
  (FaithfulSMul.algebraMap_injective
      (SourceRing R ι)
      (PolynomialSourceFunctionField (R := R) (ι := ι))).comp
    (FaithfulSMul.algebraMap_injective
      (polynomialMapImageAlgebra F) (SourceRing R ι))

/-- The induced embedding from the base function field to the source function field. -/
noncomputable def polynomialBaseFunctionFieldEmbedding
    {R : Type u} [CommRing R] [IsDomain R] {ι κ : Type v}
    (F : κ → SourceRing R ι) :
    PolynomialBaseFunctionField F →+*
      PolynomialSourceFunctionField (R := R) (ι := ι) :=
  IsFractionRing.lift
    (polynomialMapImageAlgebraToFunctionField_injective F)

/-- The function-field extension induced by `F`. -/
noncomputable def polynomialBaseFunctionFieldAlgebra
    {R : Type u} [CommRing R] [IsDomain R] {ι κ : Type v}
    (F : κ → SourceRing R ι) :
    Algebra
      (PolynomialBaseFunctionField F)
      (PolynomialSourceFunctionField (R := R) (ι := ι)) :=
  (polynomialBaseFunctionFieldEmbedding F).toAlgebra

noncomputable instance
    {R : Type u} [CommRing R] [IsDomain R] {ι κ : Type v}
    (F : κ → SourceRing R ι) :
    Algebra
      (PolynomialBaseFunctionField F)
      (PolynomialSourceFunctionField (R := R) (ι := ι)) :=
  polynomialBaseFunctionFieldAlgebra F

/-- A polynomial self-map of affine `n`-space over `R`. -/
abbrev PolynomialSelfMap (R : Type u) [CommRing R] (n : ℕ) :=
  Fin n → SourceRing R (Fin n)

/-- The Jacobian matrix of a polynomial self-map. -/
def jacobianMatrix
    {R : Type u} [CommRing R] {n : ℕ}
    (F : PolynomialSelfMap R n) :
    Matrix (Fin n) (Fin n) (SourceRing R (Fin n)) :=
  fun i j ↦ pderiv j (F i)

/-- The Jacobian determinant of a polynomial self-map. -/
def jacobianDet
    {R : Type u} [CommRing R] {n : ℕ}
    (F : PolynomialSelfMap R n) : SourceRing R (Fin n) :=
  Matrix.det (jacobianMatrix F)

/-- A Keller map has constant nonzero Jacobian determinant. -/
def IsKeller
    {K : Type u} [Field K] {n : ℕ}
    (F : PolynomialSelfMap K n) : Prop :=
  ∃ c : K, c ≠ 0 ∧ jacobianDet F = C c

/-- Polynomial automorphy means bijectivity of substitution by the coordinates. -/
def IsPolynomialAutomorphism
    {R : Type u} [CommRing R] {ι : Type v}
    (F : ι → SourceRing R ι) : Prop :=
  Function.Bijective (MvPolynomial.bind₁ F)

/-- A polynomial self-map of complex affine `n`-space. -/
abbrev ComplexPolynomialSelfMap (n : ℕ) := PolynomialSelfMap ℂ n

/-- A polynomial self-map of the complex affine plane. -/
abbrev PlanarPolynomialMap := PolynomialSelfMap ℂ 2

/-- A planar Keller map has constant nonzero Jacobian determinant. -/
abbrev IsPlanarKeller (F : PlanarPolynomialMap) : Prop := IsKeller F

/--
Keller--Galois rigidity: a complex Keller map with normal induced
function-field extension is a polynomial automorphism.
-/
def ComplexKellerGaloisRigidity (n : ℕ) : Prop :=
  ∀ F : ComplexPolynomialSelfMap n,
    IsKeller F →
      Normal
        (PolynomialBaseFunctionField F)
        (PolynomialSourceFunctionField (R := ℂ) (ι := Fin n)) →
      IsPolynomialAutomorphism F

/-- The finrank of the marked planar function-field extension. -/
def planarGenericDegree (F : PlanarPolynomialMap) : ℕ :=
  Module.finrank
    (PolynomialBaseFunctionField F)
    (PolynomialSourceFunctionField (R := ℂ) (ι := Fin 2))

namespace Palomar.PaperTwo

/- The ordered divided differences used in the planar secant projector. -/
namespace ExplicitSecant

def powDifferenceFactor
    (x y : PairRing ℂ (Fin 2)) (n : ℕ) : PairRing ℂ (Fin 2) :=
  (Polynomial.powSubPowFactor x y n).1

def firstCoefficient
    (v : Fin 2 →₀ ℕ) (r : ℂ) : PairRing ℂ (Fin 2) :=
  C r *
    powDifferenceFactor (X (Sum.inl 0)) (X (Sum.inr 0)) (v 0) *
    X (Sum.inl 1) ^ v 1

def secondCoefficient
    (v : Fin 2 →₀ ℕ) (r : ℂ) : PairRing ℂ (Fin 2) :=
  C r * X (Sum.inr 0) ^ v 0 *
    powDifferenceFactor (X (Sum.inl 1)) (X (Sum.inr 1)) (v 1)

def first (p : SourceRing ℂ (Fin 2)) : PairRing ℂ (Fin 2) :=
  p.sum firstCoefficient

def second (p : SourceRing ℂ (Fin 2)) : PairRing ℂ (Fin 2) :=
  p.sum secondCoefficient

def determinant (F : PlanarPolynomialMap) : PairRing ℂ (Fin 2) :=
  first (F 0) * second (F 1) - second (F 0) * first (F 1)

noncomputable def collisionConstantUnit
    (F : PlanarPolynomialMap) (c : ℂ) (hc : c ≠ 0) :
    (CollisionRing F)ˣ :=
  Units.map
    (Ideal.Quotient.mk (collisionIdeal F)).toMonoidHom
    (Units.map MvPolynomial.C.toMonoidHom (Units.mk0 c hc))

/-- The formula `1 - c⁻¹[δ_F]` for the off-diagonal collision
projector. -/
noncomputable def collisionProjector
    (F : PlanarPolynomialMap) (c : ℂ) (hc : c ≠ 0) :
    CollisionRing F :=
  1 -
    (↑((collisionConstantUnit F c hc)⁻¹) : CollisionRing F) *
      Ideal.Quotient.mk (collisionIdeal F) (determinant F)

end ExplicitSecant

/--
The explicit ordered divided-difference formula is an idempotent generator
of the collision obstruction.  Its complementary idempotent generates the
annihilator.
-/
theorem explicitPlanarSecantProjector
    (F : PlanarPolynomialMap)
    (c : ℂ) (hc : c ≠ 0)
    (hJacobian : jacobianDet F = C c) :
    IsIdempotentElem
        (ExplicitSecant.collisionProjector F c hc) ∧
      obstructionIdeal F =
        Ideal.span {ExplicitSecant.collisionProjector F c hc} ∧
      (obstructionIdeal F).annihilator =
        Ideal.span
          {1 - ExplicitSecant.collisionProjector F c hc} ∧
      ∀ u : CollisionRing F,
        IsIdempotentElem u →
        obstructionIdeal F = Ideal.span {u} →
        u = ExplicitSecant.collisionProjector F c hc := by
  sorry

/--
Assuming Keller--Galois rigidity, every planar map of generic degree two has
nonzero collision obstruction and is not Keller.
-/
theorem quadraticPlanarCollisionRigidity
    (hRigidity : ComplexKellerGaloisRigidity 2)
    (F : PlanarPolynomialMap)
    (hDegree : planarGenericDegree F = 2) :
    obstructionIdeal F ≠ ⊥ ∧ ¬ IsPlanarKeller F := by
  sorry

end Palomar.PaperTwo

end

end CollisionIdeals
