import CollisionIdeals.General.Galois.ConjugateAlgebra
import CollisionIdeals.General.Galois.Descent

/-!
# The fraction field of the all-conjugate algebra

The algebra generated by the conjugate polynomial sheets has the supplied
normal closure as its fraction field. The proof uses the existing normal
closure's generation property, not a Keller hypothesis or coordinate
descent to the original source field. This is not module-finiteness over
the coordinate-image base, nor an identification of the invariant open.
-/

set_option autoImplicit false

namespace CollisionIdeals

noncomputable section

universe u

variable {k : Type u} [Field k] {n : ℕ}
variable {F : PolynomialSelfMap k n}
variable {N : Type u} [Field N]
variable [Algebra (PolynomialMapBaseFunctionField F) N]

/-- The conjugate polynomial sheets generate the whole normal closure as
a field, even though they need not generate it as a ring. -/
theorem polynomialConjugateAlgebra_subfieldClosure_eq_top
    (D : PolynomialNormalClosureData F N) :
    Subfield.closure (polynomialConjugateAlgebra D : Set N) = ⊤ := by
  let B := PolynomialImageAlgebra F
  let K := PolynomialMapBaseFunctionField F
  letI : Algebra B N := polynomialNormalExtensionBaseAlgebra (F := F) (N := N)
  let E := polynomialConjugateAlgebra D
  let T := Subfield.closure (E : Set N)
  have hBase (x : K) : algebraMap K N x ∈ T := by
    obtain ⟨a, b, _hb, hab⟩ := IsFractionRing.div_surjective (A := B) x
    rw [← hab, map_div₀]
    exact T.div_mem (Subfield.subset_closure (E.algebraMap_mem a))
      (Subfield.subset_closure (E.algebraMap_mem b))
  let T' : IntermediateField K N := { T with algebraMap_mem' := hBase }
  have hTop : T' = ⊤ := by
    apply D.eq_top_of_conjugate_mem
    intro g x
    obtain ⟨p, q, _hq, hpq⟩ :=
      IsFractionRing.div_surjective (A := PolynomialSourceCoordinateRing k n) x
    rw [← hpq, map_div₀, map_div₀]
    exact T.div_mem
      (Subfield.subset_closure (polynomialConjugateAlgebra_polynomial_mem D g p))
      (Subfield.subset_closure (polynomialConjugateAlgebra_polynomial_mem D g q))
  exact congrArg IntermediateField.toSubfield hTop

/-- The actual normal-closure field is a fraction field of the all-conjugate
algebra, using its existing inclusion in that field. -/
theorem polynomialConjugateAlgebra_isFractionRing
    (D : PolynomialNormalClosureData F N) :
    IsFractionRing (polynomialConjugateAlgebra D) N := by
  letI : Algebra (PolynomialImageAlgebra F) N :=
    polynomialNormalExtensionBaseAlgebra (F := F) (N := N)
  refine IsFractionRing.of_field (polynomialConjugateAlgebra D) N ?_
  intro z
  have hz : z ∈ Subfield.closure (polynomialConjugateAlgebra D : Set N) := by
    rw [polynomialConjugateAlgebra_subfieldClosure_eq_top D]
    trivial
  obtain ⟨a, ha, b, hb, hab⟩ := Subfield.mem_closure_iff.mp hz
  have hClosure : Subring.closure (polynomialConjugateAlgebra D : Set N) ≤
      (polynomialConjugateAlgebra D).toSubring :=
    Subring.closure_le.mpr fun _ hx => hx
  exact ⟨⟨a, hClosure ha⟩, ⟨b, hClosure hb⟩, hab.symm⟩

end

end CollisionIdeals
