import CollisionIdeals.General.Galois.PolynomialCollisionPair
import Mathlib.RingTheory.FiniteType

/-!
# The algebra generated by all conjugate polynomial sheets

For a marked polynomial normal closure, this constructs the actual
coordinate-image algebra `B`-subalgebra of `N` generated by the conjugate
source coordinates. It contains every conjugate polynomial source ring,
is stable under the normal-closure Galois group, and is of finite type.

Finite type here means finitely generated as an algebra, not module-finite
over `B`. This file does not assert étaleness, identify the invariant ring
with an affine open, or construct a boundary ideal.
-/

set_option autoImplicit false

namespace CollisionIdeals

open MvPolynomial

noncomputable section

universe u

variable {k : Type u} [Field k] {n : ℕ}
variable {F : PolynomialSelfMap k n}
variable {N : Type u} [Field N]
variable [Algebra (PolynomialMapBaseFunctionField F) N]

local instance conjugateAlgebraBaseAlgebra : Algebra (PolynomialImageAlgebra F) N :=
  polynomialNormalExtensionBaseAlgebra (F := F) (N := N)

/-- The `B`-algebra generated by all conjugate polynomial source coordinates. -/
def polynomialConjugateAlgebra (D : PolynomialNormalClosureData F N) :
    Subalgebra (PolynomialImageAlgebra F) N :=
  Algebra.adjoin (PolynomialImageAlgebra F)
    (Set.range fun gi : D.galoisGroup × Fin n =>
      polynomialConjugateSourceMapOverImage D gi.1 (X gi.2))

/-- Each conjugate coordinate belongs to the all-conjugate algebra. -/
theorem polynomialConjugateAlgebra_coordinate_mem
    (D : PolynomialNormalClosureData F N) (g : D.galoisGroup) (i : Fin n) :
    polynomialConjugateSourceMapOverImage D g (X i) ∈ polynomialConjugateAlgebra D :=
  Algebra.subset_adjoin ⟨(g, i), rfl⟩

/-- The finite coordinate presentation contains every conjugate polynomial,
so it is also the algebra generated by all conjugate source rings. -/
theorem polynomialConjugateAlgebra_polynomial_mem
    (D : PolynomialNormalClosureData F N) (g : D.galoisGroup)
    (p : PolynomialSourceCoordinateRing k n) :
    polynomialConjugateSourceMapOverImage D g p ∈ polynomialConjugateAlgebra D := by
  induction p using MvPolynomial.induction_on with
  | C c =>
      change polynomialConjugateSourceMapOverImage D g
        (algebraMap (PolynomialImageAlgebra F) (PolynomialSourceCoordinateRing k n)
          (algebraMap k (PolynomialImageAlgebra F) c)) ∈ polynomialConjugateAlgebra D
      rw [(polynomialConjugateSourceMapOverImage D g).commutes]
      exact (polynomialConjugateAlgebra D).algebraMap_mem _
  | add p q hp hq =>
      rw [map_add]
      exact (polynomialConjugateAlgebra D).add_mem hp hq
  | mul_X p i hp =>
      rw [map_mul]
      exact (polynomialConjugateAlgebra D).mul_mem hp
        (polynomialConjugateAlgebra_coordinate_mem D g i)

/-- Every normal-closure automorphism preserves the all-conjugate algebra. -/
theorem polynomialConjugateAlgebra_galois_mem
    (D : PolynomialNormalClosureData F N) (g : D.galoisGroup)
    {z : N} (hz : z ∈ polynomialConjugateAlgebra D) :
    g z ∈ polynomialConjugateAlgebra D := by
  refine Algebra.adjoin_induction
    (p := fun z _ => g z ∈ polynomialConjugateAlgebra D) ?_ ?_ ?_ ?_ hz
  · rintro z ⟨⟨h, i⟩, rfl⟩
    exact polynomialConjugateAlgebra_coordinate_mem D (g * h) i
  · intro b
    change g (algebraMap (PolynomialMapBaseFunctionField F) N
      (algebraMap (PolynomialImageAlgebra F) (PolynomialMapBaseFunctionField F) b)) ∈ _
    rw [g.commutes]
    exact (polynomialConjugateAlgebra D).algebraMap_mem b
  · intro x y _ _ hx hy
    rw [map_add]
    exact (polynomialConjugateAlgebra D).add_mem hx hy
  · intro x y _ _ hx hy
    rw [map_mul]
    exact (polynomialConjugateAlgebra D).mul_mem hx hy

/-- Galois stability in both directions. -/
theorem polynomialConjugateAlgebra_galois_mem_iff
    (D : PolynomialNormalClosureData F N) (g : D.galoisGroup) (z : N) :
    g z ∈ polynomialConjugateAlgebra D ↔ z ∈ polynomialConjugateAlgebra D := by
  constructor
  · intro hz
    simpa only [AlgEquiv.symm_apply_apply] using
      polynomialConjugateAlgebra_galois_mem D g.symm hz
  · exact polynomialConjugateAlgebra_galois_mem D g

/-- The algebra has a finite set of conjugate-coordinate generators. -/
theorem polynomialConjugateAlgebra_fg
    (D : PolynomialNormalClosureData F N) : (polynomialConjugateAlgebra D).FG := by
  letI : Finite D.galoisGroup := D.finiteGaloisGroup
  exact Subalgebra.fg_def.mpr
    ⟨_, Set.finite_range
      (fun gi : D.galoisGroup × Fin n =>
        polynomialConjugateSourceMapOverImage D gi.1 (X gi.2)), rfl⟩

/-- Finite generation as an algebra; this is not module-finiteness. -/
theorem polynomialConjugateAlgebra_finiteType
    (D : PolynomialNormalClosureData F N) :
    Algebra.FiniteType (PolynomialImageAlgebra F) (polynomialConjugateAlgebra D) :=
  (Subalgebra.fg_iff_finiteType _).mp (polynomialConjugateAlgebra_fg D)

end

end CollisionIdeals
