import CollisionIdeals.General.Galois.Descent
import CollisionIdeals.General.Galois.PolynomialCollisionPair

/-!
# Descent of conjugate polynomial coordinates

The marked copy of the original source function field is generated by the
source coordinates and their rational functions. A conjugate embedding
lands in this copy precisely when its source coordinates do. Applying this
to every conjugate characterizes normality of the original extension `L/K`,
not merely normality of its already-normal closure `N/K`.

These implications do not establish coordinate descent for Keller maps.
-/

set_option autoImplicit false
set_option maxHeartbeats 800000

namespace CollisionIdeals

noncomputable section

open MvPolynomial

universe u

variable {k : Type u} [Field k] {n : ℕ}
variable {F : PolynomialSelfMap k n}
variable {N : Type u} [Field N]
variable [Algebra (PolynomialMapBaseFunctionField F) N]

/-- Membership of the conjugate source coordinates in the marked original
field is equivalent to membership of all conjugate source rational functions. -/
theorem polynomialConjugate_coordinates_mem_iff
    (D : PolynomialNormalClosureData F N) (g : D.galoisGroup) :
    (∀ i : Fin n,
      g (D.embedding
        (algebraMap (SourceRing k (Fin n)) (PolynomialMapSourceFunctionField F)
          (X i))) ∈ D.intermediateField) ↔
      ∀ x : PolynomialMapSourceFunctionField F,
        g (D.embedding x) ∈ D.intermediateField := by
  constructor
  · intro hCoordinates
    letI : Algebra (PolynomialImageAlgebra F) N :=
      polynomialNormalExtensionBaseAlgebra (F := F) (N := N)
    have hPolynomial (p : SourceRing k (Fin n)) :
        polynomialConjugateSourceMapOverImage D g p ∈ D.intermediateField := by
      induction p using MvPolynomial.induction_on with
      | C c =>
          change polynomialConjugateSourceMapOverImage D g
            (algebraMap (PolynomialImageAlgebra F) (SourceRing k (Fin n))
              (algebraMap k (PolynomialImageAlgebra F) c)) ∈ D.intermediateField
          rw [(polynomialConjugateSourceMapOverImage D g).commutes]
          exact D.intermediateField.algebraMap_mem
            (algebraMap (PolynomialImageAlgebra F) (PolynomialMapBaseFunctionField F)
              (algebraMap k (PolynomialImageAlgebra F) c))
      | add p q hp hq =>
          rw [map_add]
          exact D.intermediateField.add_mem hp hq
      | mul_X p i hp =>
          rw [map_mul]
          exact D.intermediateField.mul_mem hp (hCoordinates i)
    intro x
    obtain ⟨p, q, _hq, hpq⟩ :=
      IsFractionRing.div_surjective (A := SourceRing k (Fin n)) x
    rw [← hpq, map_div₀, map_div₀]
    exact D.intermediateField.div_mem (hPolynomial p) (hPolynomial q)
  · intro h i
    exact h (algebraMap (SourceRing k (Fin n)) (PolynomialMapSourceFunctionField F) (X i))

/-- Normality of the original source-function-field extension is equivalent
to descent of all conjugate source coordinates to its marked copy. -/
theorem polynomialSource_normal_iff_conjugate_coordinates_mem
    (D : PolynomialNormalClosureData F N) :
    Normal (PolynomialMapBaseFunctionField F) (PolynomialMapSourceFunctionField F) ↔
      ∀ (g : D.galoisGroup) (i : Fin n),
        g (D.embedding
          (algebraMap (SourceRing k (Fin n)) (PolynomialMapSourceFunctionField F)
            (X i))) ∈ D.intermediateField := by
  rw [D.normal_iff_conjugate_mem]
  exact forall_congr' fun g => (polynomialConjugate_coordinates_mem_iff D g).symm

/-- Failure of normality produces a conjugate source coordinate moved by
an automorphism that fixes the entire marked original field. This witnesses
an off-diagonal collision; membership in the fixing subgroup alone does not
make this automorphism an inertia element or supply a common local center. -/
theorem polynomialSource_exists_moved_conjugate_coordinate_of_not_normal
    [PerfectField (PolynomialMapBaseFunctionField F)]
    (D : PolynomialNormalClosureData F N)
    (hNotNormal :
      ¬ Normal (PolynomialMapBaseFunctionField F) (PolynomialMapSourceFunctionField F)) :
    ∃ (g : D.galoisGroup) (h : D.intermediateFixingSubgroup) (i : Fin n),
      (h : D.galoisGroup)
          (g (D.embedding
            (algebraMap (SourceRing k (Fin n)) (PolynomialMapSourceFunctionField F)
              (X i)))) ≠
        g (D.embedding
          (algebraMap (SourceRing k (Fin n)) (PolynomialMapSourceFunctionField F)
            (X i))) := by
  classical
  by_contra hNoWitness
  apply hNotNormal
  apply (polynomialSource_normal_iff_conjugate_coordinates_mem D).mpr
  intro g i
  by_contra hNotMem
  obtain ⟨h, hMove⟩ := D.exists_fixingSubgroup_move_of_not_mem hNotMem
  exact hNoWitness ⟨g, h, i, hMove⟩

end

end CollisionIdeals
