import Mathlib.RingTheory.Derivation.Basic
import Mathlib.Algebra.MvPolynomial.CommRing
import Mathlib.RingTheory.Localization.FractionRing
import Mathlib.RingTheory.Ideal.Span
import Mathlib.Tactic.FieldSimp
import Mathlib.Tactic.Ring
import Mathlib.Tactic.LinearCombination
import CollisionIdeals.General.Normalization.BaseTransversality

/-!
# Derivations and a simple-pole module

For a nonzero element `s` of a domain, the cyclic submodule generated by
`1 / s` in its fraction field consists of fractions with denominator `s`.
An extended derivation preserves this module if and only if its base
derivation preserves the principal ideal `(s)`.

This algebraic criterion does not assert that a Keller frame preserves a
particular boundary ideal, nor that a chosen denominator cuts out the actual
boundary. Both are separate geometric requirements.
-/

set_option autoImplicit false

namespace CollisionIdeals

noncomputable section

section General

variable {k B K : Type*} [CommRing k] [CommRing B] [IsDomain B] [Field K]
  [Algebra k B] [Algebra k K] [Algebra B K] [IsFractionRing B K]

/-- The derivative of a simple-pole generator still has denominator `s`
exactly when the derivative of `s` belongs to its principal ideal. -/
theorem derivation_inv_mem_span_singleton_iff
    (d : Derivation k B B) (D : Derivation k K K)
    (hD : ∀ b, D (algebraMap B K b) = algebraMap B K (d b))
    {s : B} (hs : s ≠ 0) :
    D ((algebraMap B K s)⁻¹) ∈
        Submodule.span B ({(algebraMap B K s)⁻¹} : Set K) ↔
      d s ∈ Ideal.span ({s} : Set B) := by
  have hsK : algebraMap B K s ≠ 0 :=
    fun h => hs (IsFractionRing.injective B K (by simpa using h))
  rw [Submodule.mem_span_singleton, Ideal.mem_span_singleton']
  simp only [D.leibniz_inv, hD, smul_eq_mul, Algebra.smul_def]
  constructor
  · rintro ⟨b, hb⟩
    refine ⟨-b, IsFractionRing.injective B K ?_⟩
    simp only [map_mul, map_neg]
    field_simp [hsK] at hb
    linear_combination -hb
  · rintro ⟨b, hb⟩
    refine ⟨-b, ?_⟩
    have hbK := congrArg (algebraMap B K) hb
    simp only [map_mul] at hbK
    rw [map_neg, ← hbK]
    field_simp [hsK]

/-- Since the base derivation maps `B` to `B`, preservation of the cyclic
simple-pole module can be tested on its single generator. -/
theorem derivation_preserves_span_inv_iff
    (d : Derivation k B B) (D : Derivation k K K)
    (hD : ∀ b, D (algebraMap B K b) = algebraMap B K (d b))
    {s : B} (hs : s ≠ 0) :
    (∀ z ∈ Submodule.span B ({(algebraMap B K s)⁻¹} : Set K),
      D z ∈ Submodule.span B ({(algebraMap B K s)⁻¹} : Set K)) ↔
      d s ∈ Ideal.span ({s} : Set B) := by
  constructor
  · intro h
    exact (derivation_inv_mem_span_singleton_iff d D hD hs).mp
      (h _ (Submodule.mem_span_singleton_self _))
  · intro h z hz
    obtain ⟨b, rfl⟩ := Submodule.mem_span_singleton.mp hz
    rw [Algebra.smul_def, D.leibniz, hD]
    simp only [smul_eq_mul]
    refine Submodule.add_mem _ ?_ ?_
    · simpa only [Algebra.smul_def] using Submodule.smul_mem _ b
        ((derivation_inv_mem_span_singleton_iff d D hD hs).mpr h)
    · simpa only [mul_comm, Algebra.smul_def] using
        Submodule.smul_mem
          (Submodule.span B ({(algebraMap B K s)⁻¹} : Set K)) (d b)
          (Submodule.mem_span_singleton_self (algebraMap B K s)⁻¹)

omit [IsDomain B] in
/-- Preservation of a principal ideal is likewise tested on its generator. -/
theorem derivation_preserves_span_singleton_iff
    (d : Derivation k B B) (s : B) :
    (∀ b ∈ Ideal.span ({s} : Set B), d b ∈ Ideal.span ({s} : Set B)) ↔
      d s ∈ Ideal.span ({s} : Set B) := by
  constructor
  · intro h
    exact h s (Ideal.mem_span_singleton_self s)
  · intro h b hb
    obtain ⟨a, rfl⟩ := Ideal.mem_span_singleton'.mp hb
    rw [d.leibniz]
    exact (Ideal.span ({s} : Set B)).add_mem
      ((Ideal.span ({s} : Set B)).smul_mem a h)
      ((Ideal.span ({s} : Set B)).mul_mem_right (d a)
        (Ideal.mem_span_singleton_self s))

/-- Preservation of the simple-pole module and of its principal denominator
ideal are equivalent; neither follows from extension to the fraction field. -/
theorem derivation_preserves_span_inv_iff_preserves_ideal
    (d : Derivation k B B) (D : Derivation k K K)
    (hD : ∀ b, D (algebraMap B K b) = algebraMap B K (d b))
    {s : B} (hs : s ≠ 0) :
    (∀ z ∈ Submodule.span B ({(algebraMap B K s)⁻¹} : Set K),
      D z ∈ Submodule.span B ({(algebraMap B K s)⁻¹} : Set K)) ↔
      ∀ b ∈ Ideal.span ({s} : Set B), d b ∈ Ideal.span ({s} : Set B) :=
  (derivation_preserves_span_inv_iff d D hD hs).trans
    (derivation_preserves_span_singleton_iff d s).symm

end General

section Polynomial

variable {σ k K : Type*} [Field k] [CharZero k] [Field K]
  [Algebra k K] [Algebra (MvPolynomial σ k) K]
  [IsFractionRing (MvPolynomial σ k) K]

/-- Over a characteristic-zero polynomial base, every coordinate derivative
preserves a simple-pole generator exactly when its denominator is a unit.
The chosen polynomial need not define any geometric boundary. -/
theorem forall_derivation_inv_mem_span_singleton_iff_isUnit
    (D : σ → Derivation k K K)
    (hD : ∀ i b, D i (algebraMap (MvPolynomial σ k) K b) =
      algebraMap (MvPolynomial σ k) K (MvPolynomial.pderiv i b))
    {s : MvPolynomial σ k} (hs : s ≠ 0) :
    (∀ i, D i ((algebraMap (MvPolynomial σ k) K s)⁻¹) ∈
      Submodule.span (MvPolynomial σ k)
        ({(algebraMap (MvPolynomial σ k) K s)⁻¹} : Set K)) ↔ IsUnit s := by
  constructor
  · intro h
    apply (Ideal.span_singleton_eq_top (x := s)).mp
    by_contra htop
    have hzero : Ideal.span ({s} : Set (MvPolynomial σ k)) ≠ ⊥ :=
      fun heq => hs (Ideal.span_singleton_eq_bot.mp heq)
    obtain ⟨b, hb, i, hi⟩ :=
      exists_mem_pderiv_not_mem (Ideal.span ({s} : Set (MvPolynomial σ k))) hzero htop
    apply hi
    exact (derivation_preserves_span_singleton_iff (k := k) (B := MvPolynomial σ k)
      (MvPolynomial.pderiv i) s).mpr
      ((derivation_inv_mem_span_singleton_iff (k := k) (B := MvPolynomial σ k)
        (K := K) (MvPolynomial.pderiv i) (D i)
        (hD i) hs).mp (h i)) b hb
  · intro h i
    apply (derivation_inv_mem_span_singleton_iff (k := k) (B := MvPolynomial σ k)
      (K := K) (MvPolynomial.pderiv i) (D i)
      (hD i) hs).mpr
    rw [Ideal.span_singleton_eq_top.mpr h]
    exact Submodule.mem_top

end Polynomial

end

end CollisionIdeals
