import CollisionIdeals.General.Collision.CollisionDiagonal
import CollisionIdeals.Planar.Secant

set_option autoImplicit false

namespace CollisionIdeals

noncomputable section

/-- A chosen planar off-diagonal projector `p_F`, constructed on the Keller locus. -/
noncomputable def planarCollisionIdempotent
    (F : PlanarPolynomialMap)
    (hKeller : IsPlanarKeller F) :
    CollisionRing F :=
  Classical.choose
    (exists_collisionOffDiagonalProjector_of_isPlanarKeller F hKeller)

/-- The chosen planar idempotent is the collision off-diagonal projector. -/
theorem planarCollisionIdempotent_isProjector
    (F : PlanarPolynomialMap)
    (hKeller : IsPlanarKeller F) :
    IsCollisionOffDiagonalProjector F
      (planarCollisionIdempotent F hKeller) :=
  Classical.choose_spec
    (exists_collisionOffDiagonalProjector_of_isPlanarKeller F hKeller)

/-- The chosen collision projector satisfies `p_F² = p_F`. -/
theorem planarCollisionIdempotent_sq
    (F : PlanarPolynomialMap)
    (hKeller : IsPlanarKeller F) :
    planarCollisionIdempotent F hKeller *
        planarCollisionIdempotent F hKeller =
      planarCollisionIdempotent F hKeller :=
  (planarCollisionIdempotent_isProjector F hKeller).1

/-- The kernel of `bar μ_F` is the ideal generated by the chosen projector `p_F`. -/
theorem ker_barMu_eq_span_planarCollisionIdempotent
    (F : PlanarPolynomialMap)
    (hKeller : IsPlanarKeller F) :
    RingHom.ker (barMu F) =
      Ideal.span {planarCollisionIdempotent F hKeller} := by
  rw [collisionDiagonal_ker]
  exact (planarCollisionIdempotent_isProjector F hKeller).2

/-- The projector vanishes exactly when `bar μ_F` is injective. -/
theorem planarCollisionIdempotent_eq_zero_iff_ker_barMu_eq_bot
    (F : PlanarPolynomialMap)
    (hKeller : IsPlanarKeller F) :
    planarCollisionIdempotent F hKeller = 0 ↔
      RingHom.ker (barMu F) = ⊥ := by
  rw [ker_barMu_eq_span_planarCollisionIdempotent F hKeller,
    Ideal.span_singleton_eq_bot]

end

end CollisionIdeals
